packages:
  - .
  - packages/*

catalog:
  '@vitest/coverage-v8': ^4.0.16
  '@vitest/ui': ^4.0.16
  tsup: ^8.5.1
  typescript: ^5.9.3
  vite: ^7.3.0
  vite-tsconfig-paths: ^5.0.0
  vitest: ^4.0.16

hoist: true

ignoredBuiltDependencies:
  - esbuild

linkWorkspacePackages: true

lockfile: true
