// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.19.6
// source: color.proto

/* eslint-disable */

export const protobufPackage = "kaboomproto";

/** Color represents the color of a chess piece or player. */
export enum Color {
  COLOR_INVALID = 0,
  COLOR_WHITE = 1,
  COLOR_BLACK = 2,
  UNRECOGNIZED = -1,
}

export function colorFromJSON(object: any): Color {
  switch (object) {
    case 0:
    case "COLOR_INVALID":
      return Color.COLOR_INVALID;
    case 1:
    case "COLOR_WHITE":
      return Color.COLOR_WHITE;
    case 2:
    case "COLOR_BLACK":
      return Color.COLOR_BLACK;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Color.UNRECOGNIZED;
  }
}

export function colorToJSON(object: Color): string {
  switch (object) {
    case Color.COLOR_INVALID:
      return "COLOR_INVALID";
    case Color.COLOR_WHITE:
      return "COLOR_WHITE";
    case Color.COLOR_BLACK:
      return "COLOR_BLACK";
    case Color.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}
