// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.19.6
// source: intent.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { KaboomMove } from "./move";
import { Position, ZoneKind, zoneKindFromJSON, zoneKindToJSON } from "./position";

export const protobufPackage = "kaboomproto";

export interface Intent {
  uuid: string;
  actingPlayerUuid: string;
  pieceMove?: IntentPieceMove | undefined;
  pieceTransfer?: IntentPieceTransfer | undefined;
  resign?: IntentResign | undefined;
}

export interface IntentPieceMove {
  boardUuid: string;
  move?: KaboomMove | undefined;
}

export interface IntentPieceTransfer {
  pieceUuid: string;
  toBoardUuid: string;
  toZone: ZoneKind;
  toPosition?: Position | undefined;
}

export interface IntentResign {
  boardUuid: string;
  reason: string;
}

function createBaseIntent(): Intent {
  return { uuid: "", actingPlayerUuid: "", pieceMove: undefined, pieceTransfer: undefined, resign: undefined };
}

export const Intent = {
  encode(message: Intent, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.uuid !== "") {
      writer.uint32(10).string(message.uuid);
    }
    if (message.actingPlayerUuid !== "") {
      writer.uint32(18).string(message.actingPlayerUuid);
    }
    if (message.pieceMove !== undefined) {
      IntentPieceMove.encode(message.pieceMove, writer.uint32(82).fork()).ldelim();
    }
    if (message.pieceTransfer !== undefined) {
      IntentPieceTransfer.encode(message.pieceTransfer, writer.uint32(90).fork()).ldelim();
    }
    if (message.resign !== undefined) {
      IntentResign.encode(message.resign, writer.uint32(98).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Intent {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIntent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.uuid = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.actingPlayerUuid = reader.string();
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.pieceMove = IntentPieceMove.decode(reader, reader.uint32());
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.pieceTransfer = IntentPieceTransfer.decode(reader, reader.uint32());
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.resign = IntentResign.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Intent {
    return {
      uuid: isSet(object.uuid) ? globalThis.String(object.uuid) : "",
      actingPlayerUuid: isSet(object.actingPlayerUuid) ? globalThis.String(object.actingPlayerUuid) : "",
      pieceMove: isSet(object.pieceMove) ? IntentPieceMove.fromJSON(object.pieceMove) : undefined,
      pieceTransfer: isSet(object.pieceTransfer) ? IntentPieceTransfer.fromJSON(object.pieceTransfer) : undefined,
      resign: isSet(object.resign) ? IntentResign.fromJSON(object.resign) : undefined,
    };
  },

  toJSON(message: Intent): unknown {
    const obj: any = {};
    if (message.uuid !== "") {
      obj.uuid = message.uuid;
    }
    if (message.actingPlayerUuid !== "") {
      obj.actingPlayerUuid = message.actingPlayerUuid;
    }
    if (message.pieceMove !== undefined) {
      obj.pieceMove = IntentPieceMove.toJSON(message.pieceMove);
    }
    if (message.pieceTransfer !== undefined) {
      obj.pieceTransfer = IntentPieceTransfer.toJSON(message.pieceTransfer);
    }
    if (message.resign !== undefined) {
      obj.resign = IntentResign.toJSON(message.resign);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Intent>, I>>(base?: I): Intent {
    return Intent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Intent>, I>>(object: I): Intent {
    const message = createBaseIntent();
    message.uuid = object.uuid ?? "";
    message.actingPlayerUuid = object.actingPlayerUuid ?? "";
    message.pieceMove = (object.pieceMove !== undefined && object.pieceMove !== null)
      ? IntentPieceMove.fromPartial(object.pieceMove)
      : undefined;
    message.pieceTransfer = (object.pieceTransfer !== undefined && object.pieceTransfer !== null)
      ? IntentPieceTransfer.fromPartial(object.pieceTransfer)
      : undefined;
    message.resign = (object.resign !== undefined && object.resign !== null)
      ? IntentResign.fromPartial(object.resign)
      : undefined;
    return message;
  },
};

function createBaseIntentPieceMove(): IntentPieceMove {
  return { boardUuid: "", move: undefined };
}

export const IntentPieceMove = {
  encode(message: IntentPieceMove, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.boardUuid !== "") {
      writer.uint32(10).string(message.boardUuid);
    }
    if (message.move !== undefined) {
      KaboomMove.encode(message.move, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): IntentPieceMove {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIntentPieceMove();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.boardUuid = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.move = KaboomMove.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IntentPieceMove {
    return {
      boardUuid: isSet(object.boardUuid) ? globalThis.String(object.boardUuid) : "",
      move: isSet(object.move) ? KaboomMove.fromJSON(object.move) : undefined,
    };
  },

  toJSON(message: IntentPieceMove): unknown {
    const obj: any = {};
    if (message.boardUuid !== "") {
      obj.boardUuid = message.boardUuid;
    }
    if (message.move !== undefined) {
      obj.move = KaboomMove.toJSON(message.move);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IntentPieceMove>, I>>(base?: I): IntentPieceMove {
    return IntentPieceMove.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IntentPieceMove>, I>>(object: I): IntentPieceMove {
    const message = createBaseIntentPieceMove();
    message.boardUuid = object.boardUuid ?? "";
    message.move = (object.move !== undefined && object.move !== null)
      ? KaboomMove.fromPartial(object.move)
      : undefined;
    return message;
  },
};

function createBaseIntentPieceTransfer(): IntentPieceTransfer {
  return { pieceUuid: "", toBoardUuid: "", toZone: 0, toPosition: undefined };
}

export const IntentPieceTransfer = {
  encode(message: IntentPieceTransfer, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.pieceUuid !== "") {
      writer.uint32(10).string(message.pieceUuid);
    }
    if (message.toBoardUuid !== "") {
      writer.uint32(18).string(message.toBoardUuid);
    }
    if (message.toZone !== 0) {
      writer.uint32(24).int32(message.toZone);
    }
    if (message.toPosition !== undefined) {
      Position.encode(message.toPosition, writer.uint32(34).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): IntentPieceTransfer {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIntentPieceTransfer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.pieceUuid = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.toBoardUuid = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.toZone = reader.int32() as any;
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.toPosition = Position.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IntentPieceTransfer {
    return {
      pieceUuid: isSet(object.pieceUuid) ? globalThis.String(object.pieceUuid) : "",
      toBoardUuid: isSet(object.toBoardUuid) ? globalThis.String(object.toBoardUuid) : "",
      toZone: isSet(object.toZone) ? zoneKindFromJSON(object.toZone) : 0,
      toPosition: isSet(object.toPosition) ? Position.fromJSON(object.toPosition) : undefined,
    };
  },

  toJSON(message: IntentPieceTransfer): unknown {
    const obj: any = {};
    if (message.pieceUuid !== "") {
      obj.pieceUuid = message.pieceUuid;
    }
    if (message.toBoardUuid !== "") {
      obj.toBoardUuid = message.toBoardUuid;
    }
    if (message.toZone !== 0) {
      obj.toZone = zoneKindToJSON(message.toZone);
    }
    if (message.toPosition !== undefined) {
      obj.toPosition = Position.toJSON(message.toPosition);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IntentPieceTransfer>, I>>(base?: I): IntentPieceTransfer {
    return IntentPieceTransfer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IntentPieceTransfer>, I>>(object: I): IntentPieceTransfer {
    const message = createBaseIntentPieceTransfer();
    message.pieceUuid = object.pieceUuid ?? "";
    message.toBoardUuid = object.toBoardUuid ?? "";
    message.toZone = object.toZone ?? 0;
    message.toPosition = (object.toPosition !== undefined && object.toPosition !== null)
      ? Position.fromPartial(object.toPosition)
      : undefined;
    return message;
  },
};

function createBaseIntentResign(): IntentResign {
  return { boardUuid: "", reason: "" };
}

export const IntentResign = {
  encode(message: IntentResign, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.boardUuid !== "") {
      writer.uint32(10).string(message.boardUuid);
    }
    if (message.reason !== "") {
      writer.uint32(18).string(message.reason);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): IntentResign {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIntentResign();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.boardUuid = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.reason = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IntentResign {
    return {
      boardUuid: isSet(object.boardUuid) ? globalThis.String(object.boardUuid) : "",
      reason: isSet(object.reason) ? globalThis.String(object.reason) : "",
    };
  },

  toJSON(message: IntentResign): unknown {
    const obj: any = {};
    if (message.boardUuid !== "") {
      obj.boardUuid = message.boardUuid;
    }
    if (message.reason !== "") {
      obj.reason = message.reason;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IntentResign>, I>>(base?: I): IntentResign {
    return IntentResign.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IntentResign>, I>>(object: I): IntentResign {
    const message = createBaseIntentResign();
    message.boardUuid = object.boardUuid ?? "";
    message.reason = object.reason ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
