// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.19.6
// source: pawn.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { PieceType, pieceTypeFromJSON, pieceTypeToJSON } from "./piece";

export const protobufPackage = "kaboomproto";

export interface PawnMove {
  fromRow: number;
  fromCol: number;
  toRow: number;
  toCol: number;
  /** optional promotion piece type */
  promotion: PieceType;
}

export interface PawnBump {
  fromRow: number;
  fromCol: number;
  toRow: number;
  toCol: number;
  /** optional promotion piece type */
  promotion: PieceType;
}

export interface PawnKaboom {
  row: number;
  col: number;
}

function createBasePawnMove(): PawnMove {
  return { fromRow: 0, fromCol: 0, toRow: 0, toCol: 0, promotion: 0 };
}

export const PawnMove = {
  encode(message: PawnMove, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.fromRow !== 0) {
      writer.uint32(8).int32(message.fromRow);
    }
    if (message.fromCol !== 0) {
      writer.uint32(16).int32(message.fromCol);
    }
    if (message.toRow !== 0) {
      writer.uint32(24).int32(message.toRow);
    }
    if (message.toCol !== 0) {
      writer.uint32(32).int32(message.toCol);
    }
    if (message.promotion !== 0) {
      writer.uint32(40).int32(message.promotion);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): PawnMove {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePawnMove();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.fromRow = reader.int32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.fromCol = reader.int32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.toRow = reader.int32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.toCol = reader.int32();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.promotion = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PawnMove {
    return {
      fromRow: isSet(object.fromRow) ? globalThis.Number(object.fromRow) : 0,
      fromCol: isSet(object.fromCol) ? globalThis.Number(object.fromCol) : 0,
      toRow: isSet(object.toRow) ? globalThis.Number(object.toRow) : 0,
      toCol: isSet(object.toCol) ? globalThis.Number(object.toCol) : 0,
      promotion: isSet(object.promotion) ? pieceTypeFromJSON(object.promotion) : 0,
    };
  },

  toJSON(message: PawnMove): unknown {
    const obj: any = {};
    if (message.fromRow !== 0) {
      obj.fromRow = Math.round(message.fromRow);
    }
    if (message.fromCol !== 0) {
      obj.fromCol = Math.round(message.fromCol);
    }
    if (message.toRow !== 0) {
      obj.toRow = Math.round(message.toRow);
    }
    if (message.toCol !== 0) {
      obj.toCol = Math.round(message.toCol);
    }
    if (message.promotion !== 0) {
      obj.promotion = pieceTypeToJSON(message.promotion);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PawnMove>, I>>(base?: I): PawnMove {
    return PawnMove.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PawnMove>, I>>(object: I): PawnMove {
    const message = createBasePawnMove();
    message.fromRow = object.fromRow ?? 0;
    message.fromCol = object.fromCol ?? 0;
    message.toRow = object.toRow ?? 0;
    message.toCol = object.toCol ?? 0;
    message.promotion = object.promotion ?? 0;
    return message;
  },
};

function createBasePawnBump(): PawnBump {
  return { fromRow: 0, fromCol: 0, toRow: 0, toCol: 0, promotion: 0 };
}

export const PawnBump = {
  encode(message: PawnBump, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.fromRow !== 0) {
      writer.uint32(8).int32(message.fromRow);
    }
    if (message.fromCol !== 0) {
      writer.uint32(16).int32(message.fromCol);
    }
    if (message.toRow !== 0) {
      writer.uint32(24).int32(message.toRow);
    }
    if (message.toCol !== 0) {
      writer.uint32(32).int32(message.toCol);
    }
    if (message.promotion !== 0) {
      writer.uint32(40).int32(message.promotion);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): PawnBump {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePawnBump();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.fromRow = reader.int32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.fromCol = reader.int32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.toRow = reader.int32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.toCol = reader.int32();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.promotion = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PawnBump {
    return {
      fromRow: isSet(object.fromRow) ? globalThis.Number(object.fromRow) : 0,
      fromCol: isSet(object.fromCol) ? globalThis.Number(object.fromCol) : 0,
      toRow: isSet(object.toRow) ? globalThis.Number(object.toRow) : 0,
      toCol: isSet(object.toCol) ? globalThis.Number(object.toCol) : 0,
      promotion: isSet(object.promotion) ? pieceTypeFromJSON(object.promotion) : 0,
    };
  },

  toJSON(message: PawnBump): unknown {
    const obj: any = {};
    if (message.fromRow !== 0) {
      obj.fromRow = Math.round(message.fromRow);
    }
    if (message.fromCol !== 0) {
      obj.fromCol = Math.round(message.fromCol);
    }
    if (message.toRow !== 0) {
      obj.toRow = Math.round(message.toRow);
    }
    if (message.toCol !== 0) {
      obj.toCol = Math.round(message.toCol);
    }
    if (message.promotion !== 0) {
      obj.promotion = pieceTypeToJSON(message.promotion);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PawnBump>, I>>(base?: I): PawnBump {
    return PawnBump.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PawnBump>, I>>(object: I): PawnBump {
    const message = createBasePawnBump();
    message.fromRow = object.fromRow ?? 0;
    message.fromCol = object.fromCol ?? 0;
    message.toRow = object.toRow ?? 0;
    message.toCol = object.toCol ?? 0;
    message.promotion = object.promotion ?? 0;
    return message;
  },
};

function createBasePawnKaboom(): PawnKaboom {
  return { row: 0, col: 0 };
}

export const PawnKaboom = {
  encode(message: PawnKaboom, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.row !== 0) {
      writer.uint32(8).int32(message.row);
    }
    if (message.col !== 0) {
      writer.uint32(16).int32(message.col);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): PawnKaboom {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePawnKaboom();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.row = reader.int32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.col = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PawnKaboom {
    return {
      row: isSet(object.row) ? globalThis.Number(object.row) : 0,
      col: isSet(object.col) ? globalThis.Number(object.col) : 0,
    };
  },

  toJSON(message: PawnKaboom): unknown {
    const obj: any = {};
    if (message.row !== 0) {
      obj.row = Math.round(message.row);
    }
    if (message.col !== 0) {
      obj.col = Math.round(message.col);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PawnKaboom>, I>>(base?: I): PawnKaboom {
    return PawnKaboom.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PawnKaboom>, I>>(object: I): PawnKaboom {
    const message = createBasePawnKaboom();
    message.row = object.row ?? 0;
    message.col = object.col ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
