// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.19.6
// source: piece.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Position } from "./position";

export const protobufPackage = "kaboomproto";

export enum PieceType {
  INVALID_PIECE = 0,
  PAWN = 1,
  KNIGHT = 2,
  BISHOP = 3,
  ROOK = 4,
  QUEEN = 5,
  KING = 6,
  UNRECOGNIZED = -1,
}

export function pieceTypeFromJSON(object: any): PieceType {
  switch (object) {
    case 0:
    case "INVALID_PIECE":
      return PieceType.INVALID_PIECE;
    case 1:
    case "PAWN":
      return PieceType.PAWN;
    case 2:
    case "KNIGHT":
      return PieceType.KNIGHT;
    case 3:
    case "BISHOP":
      return PieceType.BISHOP;
    case 4:
    case "ROOK":
      return PieceType.ROOK;
    case 5:
    case "QUEEN":
      return PieceType.QUEEN;
    case 6:
    case "KING":
      return PieceType.KING;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PieceType.UNRECOGNIZED;
  }
}

export function pieceTypeToJSON(object: PieceType): string {
  switch (object) {
    case PieceType.INVALID_PIECE:
      return "INVALID_PIECE";
    case PieceType.PAWN:
      return "PAWN";
    case PieceType.KNIGHT:
      return "KNIGHT";
    case PieceType.BISHOP:
      return "BISHOP";
    case PieceType.ROOK:
      return "ROOK";
    case PieceType.QUEEN:
      return "QUEEN";
    case PieceType.KING:
      return "KING";
    case PieceType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum Color {
  INVALID_COLOR = 0,
  WHITE = 1,
  BLACK = 2,
  UNRECOGNIZED = -1,
}

export function colorFromJSON(object: any): Color {
  switch (object) {
    case 0:
    case "INVALID_COLOR":
      return Color.INVALID_COLOR;
    case 1:
    case "WHITE":
      return Color.WHITE;
    case 2:
    case "BLACK":
      return Color.BLACK;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Color.UNRECOGNIZED;
  }
}

export function colorToJSON(object: Color): string {
  switch (object) {
    case Color.INVALID_COLOR:
      return "INVALID_COLOR";
    case Color.WHITE:
      return "WHITE";
    case Color.BLACK:
      return "BLACK";
    case Color.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface ChessPiece {
  type: PieceType;
  color: Color;
  position?: Position | undefined;
}

function createBaseChessPiece(): ChessPiece {
  return { type: 0, color: 0, position: undefined };
}

export const ChessPiece = {
  encode(message: ChessPiece, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.color !== 0) {
      writer.uint32(16).int32(message.color);
    }
    if (message.position !== undefined) {
      Position.encode(message.position, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ChessPiece {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChessPiece();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.color = reader.int32() as any;
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.position = Position.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChessPiece {
    return {
      type: isSet(object.type) ? pieceTypeFromJSON(object.type) : 0,
      color: isSet(object.color) ? colorFromJSON(object.color) : 0,
      position: isSet(object.position) ? Position.fromJSON(object.position) : undefined,
    };
  },

  toJSON(message: ChessPiece): unknown {
    const obj: any = {};
    if (message.type !== 0) {
      obj.type = pieceTypeToJSON(message.type);
    }
    if (message.color !== 0) {
      obj.color = colorToJSON(message.color);
    }
    if (message.position !== undefined) {
      obj.position = Position.toJSON(message.position);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChessPiece>, I>>(base?: I): ChessPiece {
    return ChessPiece.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChessPiece>, I>>(object: I): ChessPiece {
    const message = createBaseChessPiece();
    message.type = object.type ?? 0;
    message.color = object.color ?? 0;
    message.position = (object.position !== undefined && object.position !== null)
      ? Position.fromPartial(object.position)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
