// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.19.6
// source: visual_hint.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Position, Vector } from "./position";

export const protobufPackage = "kaboomproto";

/** VisualHint provides information for the frontend to create visual effects corresponding to game events. */
export interface VisualHint {
  uuid: string;
  boardUuid: string;
  /** Timing indicates when this visual hint should be displayed relative to other visual hints in the same TurnEffect. */
  timing: number;
  collision?: VisualHintCollision | undefined;
  explosion?: VisualHintExplosion | undefined;
  stomp?: VisualHintStomp | undefined;
  snipe?: VisualHintSnipe | undefined;
  nova?: VisualHintNova | undefined;
  mindControl?: VisualHintMindControl | undefined;
  disintegration?: VisualHintDisintegration | undefined;
  yeet?: VisualHintYeet | undefined;
}

/** VisualHint__Collision indicates a visual effect for two pieces colliding (e.g., during a bump). */
export interface VisualHintCollision {
  pieceAUuid: string;
  pieceBUuid: string;
}

/** VisualHint__Explosion indicates a visual effect for an explosion at a specific position (e.g. a pawn exploding). */
export interface VisualHintExplosion {
  position?: Position | undefined;
}

/** VisualHint__Stomp indicates a visual effect for a piece stomping on a position (e.g. knight stomp) */
export interface VisualHintStomp {
  position?: Position | undefined;
}

/** VisualHint__Snipe indicates a visual effect for a piece sniping another piece from a distance (e.g. bishop snipe). */
export interface VisualHintSnipe {
  from?: Position | undefined;
  to?: Position | undefined;
}

/** VisualHint__Nova indicates a visual effect for a nova explosion at a specific position (e.g. queen nova). */
export interface VisualHintNova {
  position?: Position | undefined;
}

/** VisualHint__MindControl indicates a visual effect for mind control between two pieces (e.g. king control). */
export interface VisualHintMindControl {
  pieceAUuid: string;
  pieceBUuid: string;
}

/** VisualHint__Disintegration indicates a visual effect for a piece disintegrating (e.g. classic chess capture, queen nova). */
export interface VisualHintDisintegration {
  pieceUuid: string;
}

/** VisualHint__Yeet indicates a visual effect for a piece being yeeted off the board (e.g. kaboom capture). */
export interface VisualHintYeet {
  pieceUuid: string;
  yeetVector?: Vector | undefined;
}

function createBaseVisualHint(): VisualHint {
  return {
    uuid: "",
    boardUuid: "",
    timing: 0,
    collision: undefined,
    explosion: undefined,
    stomp: undefined,
    snipe: undefined,
    nova: undefined,
    mindControl: undefined,
    disintegration: undefined,
    yeet: undefined,
  };
}

export const VisualHint = {
  encode(message: VisualHint, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.uuid !== "") {
      writer.uint32(10).string(message.uuid);
    }
    if (message.boardUuid !== "") {
      writer.uint32(18).string(message.boardUuid);
    }
    if (message.timing !== 0) {
      writer.uint32(24).int32(message.timing);
    }
    if (message.collision !== undefined) {
      VisualHintCollision.encode(message.collision, writer.uint32(82).fork()).ldelim();
    }
    if (message.explosion !== undefined) {
      VisualHintExplosion.encode(message.explosion, writer.uint32(90).fork()).ldelim();
    }
    if (message.stomp !== undefined) {
      VisualHintStomp.encode(message.stomp, writer.uint32(98).fork()).ldelim();
    }
    if (message.snipe !== undefined) {
      VisualHintSnipe.encode(message.snipe, writer.uint32(106).fork()).ldelim();
    }
    if (message.nova !== undefined) {
      VisualHintNova.encode(message.nova, writer.uint32(114).fork()).ldelim();
    }
    if (message.mindControl !== undefined) {
      VisualHintMindControl.encode(message.mindControl, writer.uint32(122).fork()).ldelim();
    }
    if (message.disintegration !== undefined) {
      VisualHintDisintegration.encode(message.disintegration, writer.uint32(130).fork()).ldelim();
    }
    if (message.yeet !== undefined) {
      VisualHintYeet.encode(message.yeet, writer.uint32(138).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): VisualHint {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVisualHint();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.uuid = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.boardUuid = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.timing = reader.int32();
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.collision = VisualHintCollision.decode(reader, reader.uint32());
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.explosion = VisualHintExplosion.decode(reader, reader.uint32());
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.stomp = VisualHintStomp.decode(reader, reader.uint32());
          continue;
        case 13:
          if (tag !== 106) {
            break;
          }

          message.snipe = VisualHintSnipe.decode(reader, reader.uint32());
          continue;
        case 14:
          if (tag !== 114) {
            break;
          }

          message.nova = VisualHintNova.decode(reader, reader.uint32());
          continue;
        case 15:
          if (tag !== 122) {
            break;
          }

          message.mindControl = VisualHintMindControl.decode(reader, reader.uint32());
          continue;
        case 16:
          if (tag !== 130) {
            break;
          }

          message.disintegration = VisualHintDisintegration.decode(reader, reader.uint32());
          continue;
        case 17:
          if (tag !== 138) {
            break;
          }

          message.yeet = VisualHintYeet.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VisualHint {
    return {
      uuid: isSet(object.uuid) ? globalThis.String(object.uuid) : "",
      boardUuid: isSet(object.boardUuid) ? globalThis.String(object.boardUuid) : "",
      timing: isSet(object.timing) ? globalThis.Number(object.timing) : 0,
      collision: isSet(object.collision) ? VisualHintCollision.fromJSON(object.collision) : undefined,
      explosion: isSet(object.explosion) ? VisualHintExplosion.fromJSON(object.explosion) : undefined,
      stomp: isSet(object.stomp) ? VisualHintStomp.fromJSON(object.stomp) : undefined,
      snipe: isSet(object.snipe) ? VisualHintSnipe.fromJSON(object.snipe) : undefined,
      nova: isSet(object.nova) ? VisualHintNova.fromJSON(object.nova) : undefined,
      mindControl: isSet(object.mindControl) ? VisualHintMindControl.fromJSON(object.mindControl) : undefined,
      disintegration: isSet(object.disintegration)
        ? VisualHintDisintegration.fromJSON(object.disintegration)
        : undefined,
      yeet: isSet(object.yeet) ? VisualHintYeet.fromJSON(object.yeet) : undefined,
    };
  },

  toJSON(message: VisualHint): unknown {
    const obj: any = {};
    if (message.uuid !== "") {
      obj.uuid = message.uuid;
    }
    if (message.boardUuid !== "") {
      obj.boardUuid = message.boardUuid;
    }
    if (message.timing !== 0) {
      obj.timing = Math.round(message.timing);
    }
    if (message.collision !== undefined) {
      obj.collision = VisualHintCollision.toJSON(message.collision);
    }
    if (message.explosion !== undefined) {
      obj.explosion = VisualHintExplosion.toJSON(message.explosion);
    }
    if (message.stomp !== undefined) {
      obj.stomp = VisualHintStomp.toJSON(message.stomp);
    }
    if (message.snipe !== undefined) {
      obj.snipe = VisualHintSnipe.toJSON(message.snipe);
    }
    if (message.nova !== undefined) {
      obj.nova = VisualHintNova.toJSON(message.nova);
    }
    if (message.mindControl !== undefined) {
      obj.mindControl = VisualHintMindControl.toJSON(message.mindControl);
    }
    if (message.disintegration !== undefined) {
      obj.disintegration = VisualHintDisintegration.toJSON(message.disintegration);
    }
    if (message.yeet !== undefined) {
      obj.yeet = VisualHintYeet.toJSON(message.yeet);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VisualHint>, I>>(base?: I): VisualHint {
    return VisualHint.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VisualHint>, I>>(object: I): VisualHint {
    const message = createBaseVisualHint();
    message.uuid = object.uuid ?? "";
    message.boardUuid = object.boardUuid ?? "";
    message.timing = object.timing ?? 0;
    message.collision = (object.collision !== undefined && object.collision !== null)
      ? VisualHintCollision.fromPartial(object.collision)
      : undefined;
    message.explosion = (object.explosion !== undefined && object.explosion !== null)
      ? VisualHintExplosion.fromPartial(object.explosion)
      : undefined;
    message.stomp = (object.stomp !== undefined && object.stomp !== null)
      ? VisualHintStomp.fromPartial(object.stomp)
      : undefined;
    message.snipe = (object.snipe !== undefined && object.snipe !== null)
      ? VisualHintSnipe.fromPartial(object.snipe)
      : undefined;
    message.nova = (object.nova !== undefined && object.nova !== null)
      ? VisualHintNova.fromPartial(object.nova)
      : undefined;
    message.mindControl = (object.mindControl !== undefined && object.mindControl !== null)
      ? VisualHintMindControl.fromPartial(object.mindControl)
      : undefined;
    message.disintegration = (object.disintegration !== undefined && object.disintegration !== null)
      ? VisualHintDisintegration.fromPartial(object.disintegration)
      : undefined;
    message.yeet = (object.yeet !== undefined && object.yeet !== null)
      ? VisualHintYeet.fromPartial(object.yeet)
      : undefined;
    return message;
  },
};

function createBaseVisualHintCollision(): VisualHintCollision {
  return { pieceAUuid: "", pieceBUuid: "" };
}

export const VisualHintCollision = {
  encode(message: VisualHintCollision, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.pieceAUuid !== "") {
      writer.uint32(18).string(message.pieceAUuid);
    }
    if (message.pieceBUuid !== "") {
      writer.uint32(26).string(message.pieceBUuid);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): VisualHintCollision {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVisualHintCollision();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2:
          if (tag !== 18) {
            break;
          }

          message.pieceAUuid = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.pieceBUuid = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VisualHintCollision {
    return {
      pieceAUuid: isSet(object.pieceAUuid) ? globalThis.String(object.pieceAUuid) : "",
      pieceBUuid: isSet(object.pieceBUuid) ? globalThis.String(object.pieceBUuid) : "",
    };
  },

  toJSON(message: VisualHintCollision): unknown {
    const obj: any = {};
    if (message.pieceAUuid !== "") {
      obj.pieceAUuid = message.pieceAUuid;
    }
    if (message.pieceBUuid !== "") {
      obj.pieceBUuid = message.pieceBUuid;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VisualHintCollision>, I>>(base?: I): VisualHintCollision {
    return VisualHintCollision.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VisualHintCollision>, I>>(object: I): VisualHintCollision {
    const message = createBaseVisualHintCollision();
    message.pieceAUuid = object.pieceAUuid ?? "";
    message.pieceBUuid = object.pieceBUuid ?? "";
    return message;
  },
};

function createBaseVisualHintExplosion(): VisualHintExplosion {
  return { position: undefined };
}

export const VisualHintExplosion = {
  encode(message: VisualHintExplosion, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.position !== undefined) {
      Position.encode(message.position, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): VisualHintExplosion {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVisualHintExplosion();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2:
          if (tag !== 18) {
            break;
          }

          message.position = Position.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VisualHintExplosion {
    return { position: isSet(object.position) ? Position.fromJSON(object.position) : undefined };
  },

  toJSON(message: VisualHintExplosion): unknown {
    const obj: any = {};
    if (message.position !== undefined) {
      obj.position = Position.toJSON(message.position);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VisualHintExplosion>, I>>(base?: I): VisualHintExplosion {
    return VisualHintExplosion.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VisualHintExplosion>, I>>(object: I): VisualHintExplosion {
    const message = createBaseVisualHintExplosion();
    message.position = (object.position !== undefined && object.position !== null)
      ? Position.fromPartial(object.position)
      : undefined;
    return message;
  },
};

function createBaseVisualHintStomp(): VisualHintStomp {
  return { position: undefined };
}

export const VisualHintStomp = {
  encode(message: VisualHintStomp, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.position !== undefined) {
      Position.encode(message.position, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): VisualHintStomp {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVisualHintStomp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.position = Position.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VisualHintStomp {
    return { position: isSet(object.position) ? Position.fromJSON(object.position) : undefined };
  },

  toJSON(message: VisualHintStomp): unknown {
    const obj: any = {};
    if (message.position !== undefined) {
      obj.position = Position.toJSON(message.position);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VisualHintStomp>, I>>(base?: I): VisualHintStomp {
    return VisualHintStomp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VisualHintStomp>, I>>(object: I): VisualHintStomp {
    const message = createBaseVisualHintStomp();
    message.position = (object.position !== undefined && object.position !== null)
      ? Position.fromPartial(object.position)
      : undefined;
    return message;
  },
};

function createBaseVisualHintSnipe(): VisualHintSnipe {
  return { from: undefined, to: undefined };
}

export const VisualHintSnipe = {
  encode(message: VisualHintSnipe, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.from !== undefined) {
      Position.encode(message.from, writer.uint32(18).fork()).ldelim();
    }
    if (message.to !== undefined) {
      Position.encode(message.to, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): VisualHintSnipe {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVisualHintSnipe();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2:
          if (tag !== 18) {
            break;
          }

          message.from = Position.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.to = Position.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VisualHintSnipe {
    return {
      from: isSet(object.from) ? Position.fromJSON(object.from) : undefined,
      to: isSet(object.to) ? Position.fromJSON(object.to) : undefined,
    };
  },

  toJSON(message: VisualHintSnipe): unknown {
    const obj: any = {};
    if (message.from !== undefined) {
      obj.from = Position.toJSON(message.from);
    }
    if (message.to !== undefined) {
      obj.to = Position.toJSON(message.to);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VisualHintSnipe>, I>>(base?: I): VisualHintSnipe {
    return VisualHintSnipe.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VisualHintSnipe>, I>>(object: I): VisualHintSnipe {
    const message = createBaseVisualHintSnipe();
    message.from = (object.from !== undefined && object.from !== null) ? Position.fromPartial(object.from) : undefined;
    message.to = (object.to !== undefined && object.to !== null) ? Position.fromPartial(object.to) : undefined;
    return message;
  },
};

function createBaseVisualHintNova(): VisualHintNova {
  return { position: undefined };
}

export const VisualHintNova = {
  encode(message: VisualHintNova, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.position !== undefined) {
      Position.encode(message.position, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): VisualHintNova {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVisualHintNova();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2:
          if (tag !== 18) {
            break;
          }

          message.position = Position.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VisualHintNova {
    return { position: isSet(object.position) ? Position.fromJSON(object.position) : undefined };
  },

  toJSON(message: VisualHintNova): unknown {
    const obj: any = {};
    if (message.position !== undefined) {
      obj.position = Position.toJSON(message.position);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VisualHintNova>, I>>(base?: I): VisualHintNova {
    return VisualHintNova.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VisualHintNova>, I>>(object: I): VisualHintNova {
    const message = createBaseVisualHintNova();
    message.position = (object.position !== undefined && object.position !== null)
      ? Position.fromPartial(object.position)
      : undefined;
    return message;
  },
};

function createBaseVisualHintMindControl(): VisualHintMindControl {
  return { pieceAUuid: "", pieceBUuid: "" };
}

export const VisualHintMindControl = {
  encode(message: VisualHintMindControl, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.pieceAUuid !== "") {
      writer.uint32(18).string(message.pieceAUuid);
    }
    if (message.pieceBUuid !== "") {
      writer.uint32(26).string(message.pieceBUuid);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): VisualHintMindControl {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVisualHintMindControl();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2:
          if (tag !== 18) {
            break;
          }

          message.pieceAUuid = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.pieceBUuid = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VisualHintMindControl {
    return {
      pieceAUuid: isSet(object.pieceAUuid) ? globalThis.String(object.pieceAUuid) : "",
      pieceBUuid: isSet(object.pieceBUuid) ? globalThis.String(object.pieceBUuid) : "",
    };
  },

  toJSON(message: VisualHintMindControl): unknown {
    const obj: any = {};
    if (message.pieceAUuid !== "") {
      obj.pieceAUuid = message.pieceAUuid;
    }
    if (message.pieceBUuid !== "") {
      obj.pieceBUuid = message.pieceBUuid;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VisualHintMindControl>, I>>(base?: I): VisualHintMindControl {
    return VisualHintMindControl.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VisualHintMindControl>, I>>(object: I): VisualHintMindControl {
    const message = createBaseVisualHintMindControl();
    message.pieceAUuid = object.pieceAUuid ?? "";
    message.pieceBUuid = object.pieceBUuid ?? "";
    return message;
  },
};

function createBaseVisualHintDisintegration(): VisualHintDisintegration {
  return { pieceUuid: "" };
}

export const VisualHintDisintegration = {
  encode(message: VisualHintDisintegration, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.pieceUuid !== "") {
      writer.uint32(18).string(message.pieceUuid);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): VisualHintDisintegration {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVisualHintDisintegration();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2:
          if (tag !== 18) {
            break;
          }

          message.pieceUuid = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VisualHintDisintegration {
    return { pieceUuid: isSet(object.pieceUuid) ? globalThis.String(object.pieceUuid) : "" };
  },

  toJSON(message: VisualHintDisintegration): unknown {
    const obj: any = {};
    if (message.pieceUuid !== "") {
      obj.pieceUuid = message.pieceUuid;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VisualHintDisintegration>, I>>(base?: I): VisualHintDisintegration {
    return VisualHintDisintegration.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VisualHintDisintegration>, I>>(object: I): VisualHintDisintegration {
    const message = createBaseVisualHintDisintegration();
    message.pieceUuid = object.pieceUuid ?? "";
    return message;
  },
};

function createBaseVisualHintYeet(): VisualHintYeet {
  return { pieceUuid: "", yeetVector: undefined };
}

export const VisualHintYeet = {
  encode(message: VisualHintYeet, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.pieceUuid !== "") {
      writer.uint32(18).string(message.pieceUuid);
    }
    if (message.yeetVector !== undefined) {
      Vector.encode(message.yeetVector, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): VisualHintYeet {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVisualHintYeet();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2:
          if (tag !== 18) {
            break;
          }

          message.pieceUuid = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.yeetVector = Vector.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VisualHintYeet {
    return {
      pieceUuid: isSet(object.pieceUuid) ? globalThis.String(object.pieceUuid) : "",
      yeetVector: isSet(object.yeetVector) ? Vector.fromJSON(object.yeetVector) : undefined,
    };
  },

  toJSON(message: VisualHintYeet): unknown {
    const obj: any = {};
    if (message.pieceUuid !== "") {
      obj.pieceUuid = message.pieceUuid;
    }
    if (message.yeetVector !== undefined) {
      obj.yeetVector = Vector.toJSON(message.yeetVector);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VisualHintYeet>, I>>(base?: I): VisualHintYeet {
    return VisualHintYeet.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VisualHintYeet>, I>>(object: I): VisualHintYeet {
    const message = createBaseVisualHintYeet();
    message.pieceUuid = object.pieceUuid ?? "";
    message.yeetVector = (object.yeetVector !== undefined && object.yeetVector !== null)
      ? Vector.fromPartial(object.yeetVector)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
