FROM docker.io/fedora:43 AS devcontainer

RUN dnf install -y \
    bash-completion \
    curl \
    file \
    git \
    gnupg2 \
    golang \
    hostname \
    iputils \
    jq \
    man-db \
    ncurses \
    nodejs \
    npm \
    openssh openssh-clients \
    protobuf-compiler \
    python3 \
    sudo \
    unzip \
    vim \
    wget \
    xz \
    zip


# Extra bashrc, paths, etc
COPY ./bashrc-load-dir.sh /etc/bashrc-load-dir.sh
COPY ./bashrc.d /etc/.bashrc.d
RUN printf '\n\
    if [ -d /etc/.bashrc.d ]; then\n\
    for rc in /etc/.bashrc.d/*; do\n\
    if [ -f "$rc" ]; then\n\
    . "$rc"\n\
    fi\n\
    done\n\
    fi\n\
    \n' >> /etc/bashrc


# Build arg from devcontainer.json
ARG USERNAME=developer
ARG USER_UID=1000
ARG USER_GID=${USER_UID}


# Create the user with that name
RUN groupadd --gid ${USER_GID} ${USERNAME} \
    && useradd --uid ${USER_UID} --gid ${USER_GID} -m ${USERNAME} \
    && echo "${USERNAME} ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/${USERNAME} \
    && chmod 0440 /etc/sudoers.d/${USERNAME}

USER ${USERNAME}
WORKDIR /workspace

# Install Go tools
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
