// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: board.proto

package kaboomproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Board struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Width         int64                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int64                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	PlayerColors  []*PlayerColor         `protobuf:"bytes,10,rep,name=player_colors,json=playerColors,proto3" json:"player_colors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Board) Reset() {
	*x = Board{}
	mi := &file_board_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_board_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_board_proto_rawDescGZIP(), []int{0}
}

func (x *Board) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Board) GetWidth() int64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Board) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Board) GetPlayerColors() []*PlayerColor {
	if x != nil {
		return x.PlayerColors
	}
	return nil
}

var File_board_proto protoreflect.FileDescriptor

const file_board_proto_rawDesc = "" +
	"\n" +
	"\vboard.proto\x12\vkaboomproto\x1a\vcolor.proto\"\x88\x01\n" +
	"\x05Board\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x03R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x03R\x06height\x12=\n" +
	"\rplayer_colors\x18\n" +
	" \x03(\v2\x18.kaboomproto.PlayerColorR\fplayerColorsB1Z/github.com/fsufitch/kaboom/proto/go;kaboomprotob\x06proto3"

var (
	file_board_proto_rawDescOnce sync.Once
	file_board_proto_rawDescData []byte
)

func file_board_proto_rawDescGZIP() []byte {
	file_board_proto_rawDescOnce.Do(func() {
		file_board_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_board_proto_rawDesc), len(file_board_proto_rawDesc)))
	})
	return file_board_proto_rawDescData
}

var file_board_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_board_proto_goTypes = []any{
	(*Board)(nil),       // 0: kaboomproto.Board
	(*PlayerColor)(nil), // 1: kaboomproto.PlayerColor
}
var file_board_proto_depIdxs = []int32{
	1, // 0: kaboomproto.Board.player_colors:type_name -> kaboomproto.PlayerColor
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_board_proto_init() }
func file_board_proto_init() {
	if File_board_proto != nil {
		return
	}
	file_color_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_board_proto_rawDesc), len(file_board_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_board_proto_goTypes,
		DependencyIndexes: file_board_proto_depIdxs,
		MessageInfos:      file_board_proto_msgTypes,
	}.Build()
	File_board_proto = out.File
	file_board_proto_goTypes = nil
	file_board_proto_depIdxs = nil
}
