// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: effect.proto

package kaboomproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Effect represents a single "thing that happens in the game".
// Effects are "actionable" elements of the game "state machine".
// Given a game state, you can apply an Effect to get the next state.
type Effect struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Uuid      string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	BoardUuid string                 `protobuf:"bytes,2,opt,name=board_uuid,json=boardUuid,proto3" json:"board_uuid,omitempty"`
	Why       string                 `protobuf:"bytes,3,opt,name=why,proto3" json:"why,omitempty"` // Human-readable reason for the effect; for logging/debugging.
	// The specific effect that occurs.
	//
	// Types that are valid to be assigned to EffectOneof:
	//
	//	*Effect_NothingHappens
	//	*Effect_PieceCreated
	//	*Effect_PieceDeleted
	//	*Effect_PieceMoved
	//	*Effect_PieceCaptured
	//	*Effect_PieceBumped
	//	*Effect_PiecePromoted
	//	*Effect_PieceDeployed
	//	*Effect_PieceTransfer
	//	*Effect_Win
	EffectOneof isEffect_EffectOneof `protobuf_oneof:"effect_oneof"`
	// Visual hints to help the frontend represent this effect.
	VisualHints   []*VisualHint `protobuf:"bytes,100,rep,name=visual_hints,json=visualHints,proto3" json:"visual_hints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect) Reset() {
	*x = Effect{}
	mi := &file_effect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect) ProtoMessage() {}

func (x *Effect) ProtoReflect() protoreflect.Message {
	mi := &file_effect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect.ProtoReflect.Descriptor instead.
func (*Effect) Descriptor() ([]byte, []int) {
	return file_effect_proto_rawDescGZIP(), []int{0}
}

func (x *Effect) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Effect) GetBoardUuid() string {
	if x != nil {
		return x.BoardUuid
	}
	return ""
}

func (x *Effect) GetWhy() string {
	if x != nil {
		return x.Why
	}
	return ""
}

func (x *Effect) GetEffectOneof() isEffect_EffectOneof {
	if x != nil {
		return x.EffectOneof
	}
	return nil
}

func (x *Effect) GetNothingHappens() *Effect__NothingHappens {
	if x != nil {
		if x, ok := x.EffectOneof.(*Effect_NothingHappens); ok {
			return x.NothingHappens
		}
	}
	return nil
}

func (x *Effect) GetPieceCreated() *Effect__PieceCreated {
	if x != nil {
		if x, ok := x.EffectOneof.(*Effect_PieceCreated); ok {
			return x.PieceCreated
		}
	}
	return nil
}

func (x *Effect) GetPieceDeleted() *Effect__PieceDeleted {
	if x != nil {
		if x, ok := x.EffectOneof.(*Effect_PieceDeleted); ok {
			return x.PieceDeleted
		}
	}
	return nil
}

func (x *Effect) GetPieceMoved() *Effect__PieceMoved {
	if x != nil {
		if x, ok := x.EffectOneof.(*Effect_PieceMoved); ok {
			return x.PieceMoved
		}
	}
	return nil
}

func (x *Effect) GetPieceCaptured() *Effect__PieceCaptured {
	if x != nil {
		if x, ok := x.EffectOneof.(*Effect_PieceCaptured); ok {
			return x.PieceCaptured
		}
	}
	return nil
}

func (x *Effect) GetPieceBumped() *Effect__PieceBumped {
	if x != nil {
		if x, ok := x.EffectOneof.(*Effect_PieceBumped); ok {
			return x.PieceBumped
		}
	}
	return nil
}

func (x *Effect) GetPiecePromoted() *Effect__PiecePromoted {
	if x != nil {
		if x, ok := x.EffectOneof.(*Effect_PiecePromoted); ok {
			return x.PiecePromoted
		}
	}
	return nil
}

func (x *Effect) GetPieceDeployed() *Effect__PieceDeployed {
	if x != nil {
		if x, ok := x.EffectOneof.(*Effect_PieceDeployed); ok {
			return x.PieceDeployed
		}
	}
	return nil
}

func (x *Effect) GetPieceTransfer() *Effect__PieceTransfer {
	if x != nil {
		if x, ok := x.EffectOneof.(*Effect_PieceTransfer); ok {
			return x.PieceTransfer
		}
	}
	return nil
}

func (x *Effect) GetWin() *Effect__Win {
	if x != nil {
		if x, ok := x.EffectOneof.(*Effect_Win); ok {
			return x.Win
		}
	}
	return nil
}

func (x *Effect) GetVisualHints() []*VisualHint {
	if x != nil {
		return x.VisualHints
	}
	return nil
}

type isEffect_EffectOneof interface {
	isEffect_EffectOneof()
}

type Effect_NothingHappens struct {
	NothingHappens *Effect__NothingHappens `protobuf:"bytes,10,opt,name=nothing_happens,json=nothingHappens,proto3,oneof"`
}

type Effect_PieceCreated struct {
	PieceCreated *Effect__PieceCreated `protobuf:"bytes,30,opt,name=piece_created,json=pieceCreated,proto3,oneof"`
}

type Effect_PieceDeleted struct {
	PieceDeleted *Effect__PieceDeleted `protobuf:"bytes,31,opt,name=piece_deleted,json=pieceDeleted,proto3,oneof"`
}

type Effect_PieceMoved struct {
	PieceMoved *Effect__PieceMoved `protobuf:"bytes,32,opt,name=piece_moved,json=pieceMoved,proto3,oneof"`
}

type Effect_PieceCaptured struct {
	PieceCaptured *Effect__PieceCaptured `protobuf:"bytes,33,opt,name=piece_captured,json=pieceCaptured,proto3,oneof"`
}

type Effect_PieceBumped struct {
	PieceBumped *Effect__PieceBumped `protobuf:"bytes,36,opt,name=piece_bumped,json=pieceBumped,proto3,oneof"`
}

type Effect_PiecePromoted struct {
	PiecePromoted *Effect__PiecePromoted `protobuf:"bytes,37,opt,name=piece_promoted,json=piecePromoted,proto3,oneof"`
}

type Effect_PieceDeployed struct {
	PieceDeployed *Effect__PieceDeployed `protobuf:"bytes,34,opt,name=piece_deployed,json=pieceDeployed,proto3,oneof"`
}

type Effect_PieceTransfer struct {
	PieceTransfer *Effect__PieceTransfer `protobuf:"bytes,35,opt,name=piece_transfer,json=pieceTransfer,proto3,oneof"`
}

type Effect_Win struct {
	Win *Effect__Win `protobuf:"bytes,40,opt,name=win,proto3,oneof"`
}

func (*Effect_NothingHappens) isEffect_EffectOneof() {}

func (*Effect_PieceCreated) isEffect_EffectOneof() {}

func (*Effect_PieceDeleted) isEffect_EffectOneof() {}

func (*Effect_PieceMoved) isEffect_EffectOneof() {}

func (*Effect_PieceCaptured) isEffect_EffectOneof() {}

func (*Effect_PieceBumped) isEffect_EffectOneof() {}

func (*Effect_PiecePromoted) isEffect_EffectOneof() {}

func (*Effect_PieceDeployed) isEffect_EffectOneof() {}

func (*Effect_PieceTransfer) isEffect_EffectOneof() {}

func (*Effect_Win) isEffect_EffectOneof() {}

// Effect__NothingHappens is a no-op effect; used for timing placeholders, or for visual hints that don't correspond to game state changes.
type Effect__NothingHappens struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect__NothingHappens) Reset() {
	*x = Effect__NothingHappens{}
	mi := &file_effect_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect__NothingHappens) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect__NothingHappens) ProtoMessage() {}

func (x *Effect__NothingHappens) ProtoReflect() protoreflect.Message {
	mi := &file_effect_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect__NothingHappens.ProtoReflect.Descriptor instead.
func (*Effect__NothingHappens) Descriptor() ([]byte, []int) {
	return file_effect_proto_rawDescGZIP(), []int{1}
}

// Effect__PieceCreated represents the creation of a new piece on the board.
// This is NOT equivalent to deployment, only when an entirely new piece is instantiated.
type Effect__PieceCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Piece         *ChessPiece            `protobuf:"bytes,1,opt,name=piece,proto3" json:"piece,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect__PieceCreated) Reset() {
	*x = Effect__PieceCreated{}
	mi := &file_effect_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect__PieceCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect__PieceCreated) ProtoMessage() {}

func (x *Effect__PieceCreated) ProtoReflect() protoreflect.Message {
	mi := &file_effect_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect__PieceCreated.ProtoReflect.Descriptor instead.
func (*Effect__PieceCreated) Descriptor() ([]byte, []int) {
	return file_effect_proto_rawDescGZIP(), []int{2}
}

func (x *Effect__PieceCreated) GetPiece() *ChessPiece {
	if x != nil {
		return x.Piece
	}
	return nil
}

// Effect__PieceDeleted represents the removal of a piece from the game entirely.
// This is NOT equivalent to capture, only when a piece is destroyed utterly somehow.
type Effect__PieceDeleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PieceUuid     string                 `protobuf:"bytes,1,opt,name=piece_uuid,json=pieceUuid,proto3" json:"piece_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect__PieceDeleted) Reset() {
	*x = Effect__PieceDeleted{}
	mi := &file_effect_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect__PieceDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect__PieceDeleted) ProtoMessage() {}

func (x *Effect__PieceDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_effect_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect__PieceDeleted.ProtoReflect.Descriptor instead.
func (*Effect__PieceDeleted) Descriptor() ([]byte, []int) {
	return file_effect_proto_rawDescGZIP(), []int{3}
}

func (x *Effect__PieceDeleted) GetPieceUuid() string {
	if x != nil {
		return x.PieceUuid
	}
	return ""
}

// Effect__PieceMoved represents a piece moving from one position to another on the same board.
// If the piece's movement is due to a bump action, use PieceBumped instead.
type Effect__PieceMoved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PieceUuid     string                 `protobuf:"bytes,1,opt,name=piece_uuid,json=pieceUuid,proto3" json:"piece_uuid,omitempty"`
	Vector        *Vector                `protobuf:"bytes,2,opt,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect__PieceMoved) Reset() {
	*x = Effect__PieceMoved{}
	mi := &file_effect_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect__PieceMoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect__PieceMoved) ProtoMessage() {}

func (x *Effect__PieceMoved) ProtoReflect() protoreflect.Message {
	mi := &file_effect_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect__PieceMoved.ProtoReflect.Descriptor instead.
func (*Effect__PieceMoved) Descriptor() ([]byte, []int) {
	return file_effect_proto_rawDescGZIP(), []int{4}
}

func (x *Effect__PieceMoved) GetPieceUuid() string {
	if x != nil {
		return x.PieceUuid
	}
	return ""
}

func (x *Effect__PieceMoved) GetVector() *Vector {
	if x != nil {
		return x.Vector
	}
	return nil
}

// Effect__PieceCaptured represents a piece being captured and moved to its board's graveyard zone.
type Effect__PieceCaptured struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PieceUuid     string                 `protobuf:"bytes,1,opt,name=piece_uuid,json=pieceUuid,proto3" json:"piece_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect__PieceCaptured) Reset() {
	*x = Effect__PieceCaptured{}
	mi := &file_effect_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect__PieceCaptured) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect__PieceCaptured) ProtoMessage() {}

func (x *Effect__PieceCaptured) ProtoReflect() protoreflect.Message {
	mi := &file_effect_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect__PieceCaptured.ProtoReflect.Descriptor instead.
func (*Effect__PieceCaptured) Descriptor() ([]byte, []int) {
	return file_effect_proto_rawDescGZIP(), []int{5}
}

func (x *Effect__PieceCaptured) GetPieceUuid() string {
	if x != nil {
		return x.PieceUuid
	}
	return ""
}

// Effect__PieceBumped represents a piece being bumped from one position to another on the same board.
// It is similar to Effect__PieceMoved, but specifically indicates that the piece was forced to move by another piece's action.
type Effect__PieceBumped struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PieceUuid     string                 `protobuf:"bytes,1,opt,name=piece_uuid,json=pieceUuid,proto3" json:"piece_uuid,omitempty"`
	Vector        *Vector                `protobuf:"bytes,2,opt,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect__PieceBumped) Reset() {
	*x = Effect__PieceBumped{}
	mi := &file_effect_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect__PieceBumped) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect__PieceBumped) ProtoMessage() {}

func (x *Effect__PieceBumped) ProtoReflect() protoreflect.Message {
	mi := &file_effect_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect__PieceBumped.ProtoReflect.Descriptor instead.
func (*Effect__PieceBumped) Descriptor() ([]byte, []int) {
	return file_effect_proto_rawDescGZIP(), []int{6}
}

func (x *Effect__PieceBumped) GetPieceUuid() string {
	if x != nil {
		return x.PieceUuid
	}
	return ""
}

func (x *Effect__PieceBumped) GetVector() *Vector {
	if x != nil {
		return x.Vector
	}
	return nil
}

// Effect__PiecePromoted represents a piece being promoted to a different kind (e.g., pawn to queen).
type Effect__PiecePromoted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PieceUuid     string                 `protobuf:"bytes,1,opt,name=piece_uuid,json=pieceUuid,proto3" json:"piece_uuid,omitempty"`
	ToKind        PieceKind              `protobuf:"varint,2,opt,name=to_kind,json=toKind,proto3,enum=kaboomproto.PieceKind" json:"to_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect__PiecePromoted) Reset() {
	*x = Effect__PiecePromoted{}
	mi := &file_effect_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect__PiecePromoted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect__PiecePromoted) ProtoMessage() {}

func (x *Effect__PiecePromoted) ProtoReflect() protoreflect.Message {
	mi := &file_effect_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect__PiecePromoted.ProtoReflect.Descriptor instead.
func (*Effect__PiecePromoted) Descriptor() ([]byte, []int) {
	return file_effect_proto_rawDescGZIP(), []int{7}
}

func (x *Effect__PiecePromoted) GetPieceUuid() string {
	if x != nil {
		return x.PieceUuid
	}
	return ""
}

func (x *Effect__PiecePromoted) GetToKind() PieceKind {
	if x != nil {
		return x.ToKind
	}
	return PieceKind_INVALID_PIECE
}

// Effect__PieceDeployed represents a piece being placed from the bench zone onto the board.
type Effect__PieceDeployed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PieceUuid     string                 `protobuf:"bytes,1,opt,name=piece_uuid,json=pieceUuid,proto3" json:"piece_uuid,omitempty"`
	ToPosition    *Position              `protobuf:"bytes,2,opt,name=to_position,json=toPosition,proto3" json:"to_position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect__PieceDeployed) Reset() {
	*x = Effect__PieceDeployed{}
	mi := &file_effect_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect__PieceDeployed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect__PieceDeployed) ProtoMessage() {}

func (x *Effect__PieceDeployed) ProtoReflect() protoreflect.Message {
	mi := &file_effect_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect__PieceDeployed.ProtoReflect.Descriptor instead.
func (*Effect__PieceDeployed) Descriptor() ([]byte, []int) {
	return file_effect_proto_rawDescGZIP(), []int{8}
}

func (x *Effect__PieceDeployed) GetPieceUuid() string {
	if x != nil {
		return x.PieceUuid
	}
	return ""
}

func (x *Effect__PieceDeployed) GetToPosition() *Position {
	if x != nil {
		return x.ToPosition
	}
	return nil
}

// Effect__PieceTransfer represents a full mutation of a piece's location (potentially across position, zone, and board).
// Do NOT use this for captures or deploys. Use it for handing off pieces between players' boards in bughouse, or similar.
type Effect__PieceTransfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PieceUuid     string                 `protobuf:"bytes,1,opt,name=piece_uuid,json=pieceUuid,proto3" json:"piece_uuid,omitempty"`
	ToBoardUuid   string                 `protobuf:"bytes,2,opt,name=to_board_uuid,json=toBoardUuid,proto3" json:"to_board_uuid,omitempty"`
	ToZone        ZoneKind               `protobuf:"varint,3,opt,name=to_zone,json=toZone,proto3,enum=kaboomproto.ZoneKind" json:"to_zone,omitempty"`
	ToPosition    *Position              `protobuf:"bytes,4,opt,name=to_position,json=toPosition,proto3" json:"to_position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect__PieceTransfer) Reset() {
	*x = Effect__PieceTransfer{}
	mi := &file_effect_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect__PieceTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect__PieceTransfer) ProtoMessage() {}

func (x *Effect__PieceTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_effect_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect__PieceTransfer.ProtoReflect.Descriptor instead.
func (*Effect__PieceTransfer) Descriptor() ([]byte, []int) {
	return file_effect_proto_rawDescGZIP(), []int{9}
}

func (x *Effect__PieceTransfer) GetPieceUuid() string {
	if x != nil {
		return x.PieceUuid
	}
	return ""
}

func (x *Effect__PieceTransfer) GetToBoardUuid() string {
	if x != nil {
		return x.ToBoardUuid
	}
	return ""
}

func (x *Effect__PieceTransfer) GetToZone() ZoneKind {
	if x != nil {
		return x.ToZone
	}
	return ZoneKind_ZONE_INVALID
}

func (x *Effect__PieceTransfer) GetToPosition() *Position {
	if x != nil {
		return x.ToPosition
	}
	return nil
}

// Effect__Win represents a player winning the game on a specific board.
type Effect__Win struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	WinningPlayerUuid string                 `protobuf:"bytes,1,opt,name=winning_player_uuid,json=winningPlayerUuid,proto3" json:"winning_player_uuid,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Effect__Win) Reset() {
	*x = Effect__Win{}
	mi := &file_effect_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect__Win) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect__Win) ProtoMessage() {}

func (x *Effect__Win) ProtoReflect() protoreflect.Message {
	mi := &file_effect_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect__Win.ProtoReflect.Descriptor instead.
func (*Effect__Win) Descriptor() ([]byte, []int) {
	return file_effect_proto_rawDescGZIP(), []int{10}
}

func (x *Effect__Win) GetWinningPlayerUuid() string {
	if x != nil {
		return x.WinningPlayerUuid
	}
	return ""
}

var File_effect_proto protoreflect.FileDescriptor

const file_effect_proto_rawDesc = "" +
	"\n" +
	"\feffect.proto\x12\vkaboomproto\x1a\vpiece.proto\x1a\x0eposition.proto\x1a\x11visual_hint.proto\"\xea\x06\n" +
	"\x06Effect\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1d\n" +
	"\n" +
	"board_uuid\x18\x02 \x01(\tR\tboardUuid\x12\x10\n" +
	"\x03why\x18\x03 \x01(\tR\x03why\x12N\n" +
	"\x0fnothing_happens\x18\n" +
	" \x01(\v2#.kaboomproto.Effect__NothingHappensH\x00R\x0enothingHappens\x12H\n" +
	"\rpiece_created\x18\x1e \x01(\v2!.kaboomproto.Effect__PieceCreatedH\x00R\fpieceCreated\x12H\n" +
	"\rpiece_deleted\x18\x1f \x01(\v2!.kaboomproto.Effect__PieceDeletedH\x00R\fpieceDeleted\x12B\n" +
	"\vpiece_moved\x18  \x01(\v2\x1f.kaboomproto.Effect__PieceMovedH\x00R\n" +
	"pieceMoved\x12K\n" +
	"\x0epiece_captured\x18! \x01(\v2\".kaboomproto.Effect__PieceCapturedH\x00R\rpieceCaptured\x12E\n" +
	"\fpiece_bumped\x18$ \x01(\v2 .kaboomproto.Effect__PieceBumpedH\x00R\vpieceBumped\x12K\n" +
	"\x0epiece_promoted\x18% \x01(\v2\".kaboomproto.Effect__PiecePromotedH\x00R\rpiecePromoted\x12K\n" +
	"\x0epiece_deployed\x18\" \x01(\v2\".kaboomproto.Effect__PieceDeployedH\x00R\rpieceDeployed\x12K\n" +
	"\x0epiece_transfer\x18# \x01(\v2\".kaboomproto.Effect__PieceTransferH\x00R\rpieceTransfer\x12,\n" +
	"\x03win\x18( \x01(\v2\x18.kaboomproto.Effect__WinH\x00R\x03win\x12:\n" +
	"\fvisual_hints\x18d \x03(\v2\x17.kaboomproto.VisualHintR\vvisualHintsB\x0e\n" +
	"\feffect_oneof\"\x18\n" +
	"\x16Effect__NothingHappens\"E\n" +
	"\x14Effect__PieceCreated\x12-\n" +
	"\x05piece\x18\x01 \x01(\v2\x17.kaboomproto.ChessPieceR\x05piece\"5\n" +
	"\x14Effect__PieceDeleted\x12\x1d\n" +
	"\n" +
	"piece_uuid\x18\x01 \x01(\tR\tpieceUuid\"`\n" +
	"\x12Effect__PieceMoved\x12\x1d\n" +
	"\n" +
	"piece_uuid\x18\x01 \x01(\tR\tpieceUuid\x12+\n" +
	"\x06vector\x18\x02 \x01(\v2\x13.kaboomproto.VectorR\x06vector\"6\n" +
	"\x15Effect__PieceCaptured\x12\x1d\n" +
	"\n" +
	"piece_uuid\x18\x01 \x01(\tR\tpieceUuid\"a\n" +
	"\x13Effect__PieceBumped\x12\x1d\n" +
	"\n" +
	"piece_uuid\x18\x01 \x01(\tR\tpieceUuid\x12+\n" +
	"\x06vector\x18\x02 \x01(\v2\x13.kaboomproto.VectorR\x06vector\"g\n" +
	"\x15Effect__PiecePromoted\x12\x1d\n" +
	"\n" +
	"piece_uuid\x18\x01 \x01(\tR\tpieceUuid\x12/\n" +
	"\ato_kind\x18\x02 \x01(\x0e2\x16.kaboomproto.PieceKindR\x06toKind\"n\n" +
	"\x15Effect__PieceDeployed\x12\x1d\n" +
	"\n" +
	"piece_uuid\x18\x01 \x01(\tR\tpieceUuid\x126\n" +
	"\vto_position\x18\x02 \x01(\v2\x15.kaboomproto.PositionR\n" +
	"toPosition\"\xc2\x01\n" +
	"\x15Effect__PieceTransfer\x12\x1d\n" +
	"\n" +
	"piece_uuid\x18\x01 \x01(\tR\tpieceUuid\x12\"\n" +
	"\rto_board_uuid\x18\x02 \x01(\tR\vtoBoardUuid\x12.\n" +
	"\ato_zone\x18\x03 \x01(\x0e2\x15.kaboomproto.ZoneKindR\x06toZone\x126\n" +
	"\vto_position\x18\x04 \x01(\v2\x15.kaboomproto.PositionR\n" +
	"toPosition\"=\n" +
	"\vEffect__Win\x12.\n" +
	"\x13winning_player_uuid\x18\x01 \x01(\tR\x11winningPlayerUuidB1Z/github.com/fsufitch/kaboom/proto/go;kaboomprotob\x06proto3"

var (
	file_effect_proto_rawDescOnce sync.Once
	file_effect_proto_rawDescData []byte
)

func file_effect_proto_rawDescGZIP() []byte {
	file_effect_proto_rawDescOnce.Do(func() {
		file_effect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_effect_proto_rawDesc), len(file_effect_proto_rawDesc)))
	})
	return file_effect_proto_rawDescData
}

var file_effect_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_effect_proto_goTypes = []any{
	(*Effect)(nil),                 // 0: kaboomproto.Effect
	(*Effect__NothingHappens)(nil), // 1: kaboomproto.Effect__NothingHappens
	(*Effect__PieceCreated)(nil),   // 2: kaboomproto.Effect__PieceCreated
	(*Effect__PieceDeleted)(nil),   // 3: kaboomproto.Effect__PieceDeleted
	(*Effect__PieceMoved)(nil),     // 4: kaboomproto.Effect__PieceMoved
	(*Effect__PieceCaptured)(nil),  // 5: kaboomproto.Effect__PieceCaptured
	(*Effect__PieceBumped)(nil),    // 6: kaboomproto.Effect__PieceBumped
	(*Effect__PiecePromoted)(nil),  // 7: kaboomproto.Effect__PiecePromoted
	(*Effect__PieceDeployed)(nil),  // 8: kaboomproto.Effect__PieceDeployed
	(*Effect__PieceTransfer)(nil),  // 9: kaboomproto.Effect__PieceTransfer
	(*Effect__Win)(nil),            // 10: kaboomproto.Effect__Win
	(*VisualHint)(nil),             // 11: kaboomproto.VisualHint
	(*ChessPiece)(nil),             // 12: kaboomproto.ChessPiece
	(*Vector)(nil),                 // 13: kaboomproto.Vector
	(PieceKind)(0),                 // 14: kaboomproto.PieceKind
	(*Position)(nil),               // 15: kaboomproto.Position
	(ZoneKind)(0),                  // 16: kaboomproto.ZoneKind
}
var file_effect_proto_depIdxs = []int32{
	1,  // 0: kaboomproto.Effect.nothing_happens:type_name -> kaboomproto.Effect__NothingHappens
	2,  // 1: kaboomproto.Effect.piece_created:type_name -> kaboomproto.Effect__PieceCreated
	3,  // 2: kaboomproto.Effect.piece_deleted:type_name -> kaboomproto.Effect__PieceDeleted
	4,  // 3: kaboomproto.Effect.piece_moved:type_name -> kaboomproto.Effect__PieceMoved
	5,  // 4: kaboomproto.Effect.piece_captured:type_name -> kaboomproto.Effect__PieceCaptured
	6,  // 5: kaboomproto.Effect.piece_bumped:type_name -> kaboomproto.Effect__PieceBumped
	7,  // 6: kaboomproto.Effect.piece_promoted:type_name -> kaboomproto.Effect__PiecePromoted
	8,  // 7: kaboomproto.Effect.piece_deployed:type_name -> kaboomproto.Effect__PieceDeployed
	9,  // 8: kaboomproto.Effect.piece_transfer:type_name -> kaboomproto.Effect__PieceTransfer
	10, // 9: kaboomproto.Effect.win:type_name -> kaboomproto.Effect__Win
	11, // 10: kaboomproto.Effect.visual_hints:type_name -> kaboomproto.VisualHint
	12, // 11: kaboomproto.Effect__PieceCreated.piece:type_name -> kaboomproto.ChessPiece
	13, // 12: kaboomproto.Effect__PieceMoved.vector:type_name -> kaboomproto.Vector
	13, // 13: kaboomproto.Effect__PieceBumped.vector:type_name -> kaboomproto.Vector
	14, // 14: kaboomproto.Effect__PiecePromoted.to_kind:type_name -> kaboomproto.PieceKind
	15, // 15: kaboomproto.Effect__PieceDeployed.to_position:type_name -> kaboomproto.Position
	16, // 16: kaboomproto.Effect__PieceTransfer.to_zone:type_name -> kaboomproto.ZoneKind
	15, // 17: kaboomproto.Effect__PieceTransfer.to_position:type_name -> kaboomproto.Position
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_effect_proto_init() }
func file_effect_proto_init() {
	if File_effect_proto != nil {
		return
	}
	file_piece_proto_init()
	file_position_proto_init()
	file_visual_hint_proto_init()
	file_effect_proto_msgTypes[0].OneofWrappers = []any{
		(*Effect_NothingHappens)(nil),
		(*Effect_PieceCreated)(nil),
		(*Effect_PieceDeleted)(nil),
		(*Effect_PieceMoved)(nil),
		(*Effect_PieceCaptured)(nil),
		(*Effect_PieceBumped)(nil),
		(*Effect_PiecePromoted)(nil),
		(*Effect_PieceDeployed)(nil),
		(*Effect_PieceTransfer)(nil),
		(*Effect_Win)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_effect_proto_rawDesc), len(file_effect_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_effect_proto_goTypes,
		DependencyIndexes: file_effect_proto_depIdxs,
		MessageInfos:      file_effect_proto_msgTypes,
	}.Build()
	File_effect_proto = out.File
	file_effect_proto_goTypes = nil
	file_effect_proto_depIdxs = nil
}
