// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: game.proto

package kaboomproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Game struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	RulesVariant  string                 `protobuf:"bytes,2,opt,name=rules_variant,json=rulesVariant,proto3" json:"rules_variant,omitempty"`
	Boards        []*Board               `protobuf:"bytes,20,rep,name=boards,proto3" json:"boards,omitempty"`
	Players       []*Player              `protobuf:"bytes,30,rep,name=players,proto3" json:"players,omitempty"`
	Pieces        []*ChessPiece          `protobuf:"bytes,40,rep,name=pieces,proto3" json:"pieces,omitempty"`
	Turns         []*Turn                `protobuf:"bytes,50,rep,name=turns,proto3" json:"turns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *Game) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Game) GetRulesVariant() string {
	if x != nil {
		return x.RulesVariant
	}
	return ""
}

func (x *Game) GetBoards() []*Board {
	if x != nil {
		return x.Boards
	}
	return nil
}

func (x *Game) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *Game) GetPieces() []*ChessPiece {
	if x != nil {
		return x.Pieces
	}
	return nil
}

func (x *Game) GetTurns() []*Turn {
	if x != nil {
		return x.Turns
	}
	return nil
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *Player) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Board struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Uuid              string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	WinningPlayerUuid string                 `protobuf:"bytes,5,opt,name=winning_player_uuid,json=winningPlayerUuid,proto3" json:"winning_player_uuid,omitempty"`
	PlayerColors      []*PlayerColor         `protobuf:"bytes,10,rep,name=player_colors,json=playerColors,proto3" json:"player_colors,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Board) Reset() {
	*x = Board{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *Board) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Board) GetWinningPlayerUuid() string {
	if x != nil {
		return x.WinningPlayerUuid
	}
	return ""
}

func (x *Board) GetPlayerColors() []*PlayerColor {
	if x != nil {
		return x.PlayerColors
	}
	return nil
}

type PlayerColor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerUuid    string                 `protobuf:"bytes,1,opt,name=player_uuid,json=playerUuid,proto3" json:"player_uuid,omitempty"`
	Color         Color                  `protobuf:"varint,2,opt,name=color,proto3,enum=kaboomproto.Color" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerColor) Reset() {
	*x = PlayerColor{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerColor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerColor) ProtoMessage() {}

func (x *PlayerColor) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerColor.ProtoReflect.Descriptor instead.
func (*PlayerColor) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerColor) GetPlayerUuid() string {
	if x != nil {
		return x.PlayerUuid
	}
	return ""
}

func (x *PlayerColor) GetColor() Color {
	if x != nil {
		return x.Color
	}
	return Color_COLOR_INVALID
}

// Turn represents a single turn taken by a player in the game.
// It includes the player's intents (what they "do") and the resulting effects (what "happens").
// Note: there can be multiple intents, to accommodate "bughouse" mechanics.
type Turn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	PlayerUuid    string                 `protobuf:"bytes,2,opt,name=player_uuid,json=playerUuid,proto3" json:"player_uuid,omitempty"`
	Intents       []*Intent              `protobuf:"bytes,10,rep,name=intents,proto3" json:"intents,omitempty"`
	Effects       []*Effect              `protobuf:"bytes,11,rep,name=effects,proto3" json:"effects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Turn) Reset() {
	*x = Turn{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Turn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Turn) ProtoMessage() {}

func (x *Turn) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Turn.ProtoReflect.Descriptor instead.
func (*Turn) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *Turn) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Turn) GetPlayerUuid() string {
	if x != nil {
		return x.PlayerUuid
	}
	return ""
}

func (x *Turn) GetIntents() []*Intent {
	if x != nil {
		return x.Intents
	}
	return nil
}

func (x *Turn) GetEffects() []*Effect {
	if x != nil {
		return x.Effects
	}
	return nil
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\vkaboomproto\x1a\vcolor.proto\x1a\vpiece.proto\x1a\feffect.proto\x1a\fintent.proto\"\xf4\x01\n" +
	"\x04Game\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12#\n" +
	"\rrules_variant\x18\x02 \x01(\tR\frulesVariant\x12*\n" +
	"\x06boards\x18\x14 \x03(\v2\x12.kaboomproto.BoardR\x06boards\x12-\n" +
	"\aplayers\x18\x1e \x03(\v2\x13.kaboomproto.PlayerR\aplayers\x12/\n" +
	"\x06pieces\x18( \x03(\v2\x17.kaboomproto.ChessPieceR\x06pieces\x12'\n" +
	"\x05turns\x182 \x03(\v2\x11.kaboomproto.TurnR\x05turns\"0\n" +
	"\x06Player\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x8a\x01\n" +
	"\x05Board\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12.\n" +
	"\x13winning_player_uuid\x18\x05 \x01(\tR\x11winningPlayerUuid\x12=\n" +
	"\rplayer_colors\x18\n" +
	" \x03(\v2\x18.kaboomproto.PlayerColorR\fplayerColors\"X\n" +
	"\vPlayerColor\x12\x1f\n" +
	"\vplayer_uuid\x18\x01 \x01(\tR\n" +
	"playerUuid\x12(\n" +
	"\x05color\x18\x02 \x01(\x0e2\x12.kaboomproto.ColorR\x05color\"\x99\x01\n" +
	"\x04Turn\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1f\n" +
	"\vplayer_uuid\x18\x02 \x01(\tR\n" +
	"playerUuid\x12-\n" +
	"\aintents\x18\n" +
	" \x03(\v2\x13.kaboomproto.IntentR\aintents\x12-\n" +
	"\aeffects\x18\v \x03(\v2\x13.kaboomproto.EffectR\aeffectsB1Z/github.com/fsufitch/kaboom/proto/go;kaboomprotob\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_game_proto_goTypes = []any{
	(*Game)(nil),        // 0: kaboomproto.Game
	(*Player)(nil),      // 1: kaboomproto.Player
	(*Board)(nil),       // 2: kaboomproto.Board
	(*PlayerColor)(nil), // 3: kaboomproto.PlayerColor
	(*Turn)(nil),        // 4: kaboomproto.Turn
	(*ChessPiece)(nil),  // 5: kaboomproto.ChessPiece
	(Color)(0),          // 6: kaboomproto.Color
	(*Intent)(nil),      // 7: kaboomproto.Intent
	(*Effect)(nil),      // 8: kaboomproto.Effect
}
var file_game_proto_depIdxs = []int32{
	2, // 0: kaboomproto.Game.boards:type_name -> kaboomproto.Board
	1, // 1: kaboomproto.Game.players:type_name -> kaboomproto.Player
	5, // 2: kaboomproto.Game.pieces:type_name -> kaboomproto.ChessPiece
	4, // 3: kaboomproto.Game.turns:type_name -> kaboomproto.Turn
	3, // 4: kaboomproto.Board.player_colors:type_name -> kaboomproto.PlayerColor
	6, // 5: kaboomproto.PlayerColor.color:type_name -> kaboomproto.Color
	7, // 6: kaboomproto.Turn.intents:type_name -> kaboomproto.Intent
	8, // 7: kaboomproto.Turn.effects:type_name -> kaboomproto.Effect
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	file_color_proto_init()
	file_piece_proto_init()
	file_effect_proto_init()
	file_intent_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
