// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: game.proto

package kaboomproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	RulesVariant  string                 `protobuf:"bytes,2,opt,name=rules_variant,json=rulesVariant,proto3" json:"rules_variant,omitempty"`
	Boards        []*Board               `protobuf:"bytes,20,rep,name=boards,proto3" json:"boards,omitempty"`
	Players       []*Player              `protobuf:"bytes,30,rep,name=players,proto3" json:"players,omitempty"`
	Pieces        []*ChessPiece          `protobuf:"bytes,40,rep,name=pieces,proto3" json:"pieces,omitempty"`
	Turns         []*Turn                `protobuf:"bytes,50,rep,name=turns,proto3" json:"turns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameSnapshot) Reset() {
	*x = GameSnapshot{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameSnapshot) ProtoMessage() {}

func (x *GameSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameSnapshot.ProtoReflect.Descriptor instead.
func (*GameSnapshot) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *GameSnapshot) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GameSnapshot) GetRulesVariant() string {
	if x != nil {
		return x.RulesVariant
	}
	return ""
}

func (x *GameSnapshot) GetBoards() []*Board {
	if x != nil {
		return x.Boards
	}
	return nil
}

func (x *GameSnapshot) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameSnapshot) GetPieces() []*ChessPiece {
	if x != nil {
		return x.Pieces
	}
	return nil
}

func (x *GameSnapshot) GetTurns() []*Turn {
	if x != nil {
		return x.Turns
	}
	return nil
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\vkaboomproto\x1a\vboard.proto\x1a\vpiece.proto\x1a\fplayer.proto\x1a\n" +
	"turn.proto\"\xfc\x01\n" +
	"\fGameSnapshot\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12#\n" +
	"\rrules_variant\x18\x02 \x01(\tR\frulesVariant\x12*\n" +
	"\x06boards\x18\x14 \x03(\v2\x12.kaboomproto.BoardR\x06boards\x12-\n" +
	"\aplayers\x18\x1e \x03(\v2\x13.kaboomproto.PlayerR\aplayers\x12/\n" +
	"\x06pieces\x18( \x03(\v2\x17.kaboomproto.ChessPieceR\x06pieces\x12'\n" +
	"\x05turns\x182 \x03(\v2\x11.kaboomproto.TurnR\x05turnsB1Z/github.com/fsufitch/kaboom/proto/go;kaboomprotob\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_game_proto_goTypes = []any{
	(*GameSnapshot)(nil), // 0: kaboomproto.GameSnapshot
	(*Board)(nil),        // 1: kaboomproto.Board
	(*Player)(nil),       // 2: kaboomproto.Player
	(*ChessPiece)(nil),   // 3: kaboomproto.ChessPiece
	(*Turn)(nil),         // 4: kaboomproto.Turn
}
var file_game_proto_depIdxs = []int32{
	1, // 0: kaboomproto.GameSnapshot.boards:type_name -> kaboomproto.Board
	2, // 1: kaboomproto.GameSnapshot.players:type_name -> kaboomproto.Player
	3, // 2: kaboomproto.GameSnapshot.pieces:type_name -> kaboomproto.ChessPiece
	4, // 3: kaboomproto.GameSnapshot.turns:type_name -> kaboomproto.Turn
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	file_board_proto_init()
	file_piece_proto_init()
	file_player_proto_init()
	file_turn_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
