// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: intent.proto

package kaboomproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Intent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uuid             string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ActingPlayerUuid string                 `protobuf:"bytes,2,opt,name=acting_player_uuid,json=actingPlayerUuid,proto3" json:"acting_player_uuid,omitempty"`
	PieceMove        *Intent_PieceMove      `protobuf:"bytes,10,opt,name=piece_move,json=pieceMove,proto3" json:"piece_move,omitempty"`
	PieceTransfer    *Intent_PieceTransfer  `protobuf:"bytes,11,opt,name=piece_transfer,json=pieceTransfer,proto3" json:"piece_transfer,omitempty"`
	Resign           *Intent_Resign         `protobuf:"bytes,12,opt,name=resign,proto3" json:"resign,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Intent) Reset() {
	*x = Intent{}
	mi := &file_intent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Intent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Intent) ProtoMessage() {}

func (x *Intent) ProtoReflect() protoreflect.Message {
	mi := &file_intent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Intent.ProtoReflect.Descriptor instead.
func (*Intent) Descriptor() ([]byte, []int) {
	return file_intent_proto_rawDescGZIP(), []int{0}
}

func (x *Intent) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Intent) GetActingPlayerUuid() string {
	if x != nil {
		return x.ActingPlayerUuid
	}
	return ""
}

func (x *Intent) GetPieceMove() *Intent_PieceMove {
	if x != nil {
		return x.PieceMove
	}
	return nil
}

func (x *Intent) GetPieceTransfer() *Intent_PieceTransfer {
	if x != nil {
		return x.PieceTransfer
	}
	return nil
}

func (x *Intent) GetResign() *Intent_Resign {
	if x != nil {
		return x.Resign
	}
	return nil
}

type Intent_PieceMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardUuid     string                 `protobuf:"bytes,1,opt,name=board_uuid,json=boardUuid,proto3" json:"board_uuid,omitempty"`
	Move          *KaboomMove            `protobuf:"bytes,2,opt,name=move,proto3" json:"move,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Intent_PieceMove) Reset() {
	*x = Intent_PieceMove{}
	mi := &file_intent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Intent_PieceMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Intent_PieceMove) ProtoMessage() {}

func (x *Intent_PieceMove) ProtoReflect() protoreflect.Message {
	mi := &file_intent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Intent_PieceMove.ProtoReflect.Descriptor instead.
func (*Intent_PieceMove) Descriptor() ([]byte, []int) {
	return file_intent_proto_rawDescGZIP(), []int{1}
}

func (x *Intent_PieceMove) GetBoardUuid() string {
	if x != nil {
		return x.BoardUuid
	}
	return ""
}

func (x *Intent_PieceMove) GetMove() *KaboomMove {
	if x != nil {
		return x.Move
	}
	return nil
}

type Intent_PieceTransfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PieceUuid     string                 `protobuf:"bytes,1,opt,name=piece_uuid,json=pieceUuid,proto3" json:"piece_uuid,omitempty"`
	ToBoardUuid   string                 `protobuf:"bytes,2,opt,name=to_board_uuid,json=toBoardUuid,proto3" json:"to_board_uuid,omitempty"`
	ToZone        ZoneKind               `protobuf:"varint,3,opt,name=to_zone,json=toZone,proto3,enum=kaboomproto.ZoneKind" json:"to_zone,omitempty"`
	ToPosition    *Position              `protobuf:"bytes,4,opt,name=to_position,json=toPosition,proto3" json:"to_position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Intent_PieceTransfer) Reset() {
	*x = Intent_PieceTransfer{}
	mi := &file_intent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Intent_PieceTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Intent_PieceTransfer) ProtoMessage() {}

func (x *Intent_PieceTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_intent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Intent_PieceTransfer.ProtoReflect.Descriptor instead.
func (*Intent_PieceTransfer) Descriptor() ([]byte, []int) {
	return file_intent_proto_rawDescGZIP(), []int{2}
}

func (x *Intent_PieceTransfer) GetPieceUuid() string {
	if x != nil {
		return x.PieceUuid
	}
	return ""
}

func (x *Intent_PieceTransfer) GetToBoardUuid() string {
	if x != nil {
		return x.ToBoardUuid
	}
	return ""
}

func (x *Intent_PieceTransfer) GetToZone() ZoneKind {
	if x != nil {
		return x.ToZone
	}
	return ZoneKind_ZONE_INVALID
}

func (x *Intent_PieceTransfer) GetToPosition() *Position {
	if x != nil {
		return x.ToPosition
	}
	return nil
}

type Intent_Resign struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardUuid     string                 `protobuf:"bytes,1,opt,name=board_uuid,json=boardUuid,proto3" json:"board_uuid,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Intent_Resign) Reset() {
	*x = Intent_Resign{}
	mi := &file_intent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Intent_Resign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Intent_Resign) ProtoMessage() {}

func (x *Intent_Resign) ProtoReflect() protoreflect.Message {
	mi := &file_intent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Intent_Resign.ProtoReflect.Descriptor instead.
func (*Intent_Resign) Descriptor() ([]byte, []int) {
	return file_intent_proto_rawDescGZIP(), []int{3}
}

func (x *Intent_Resign) GetBoardUuid() string {
	if x != nil {
		return x.BoardUuid
	}
	return ""
}

func (x *Intent_Resign) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_intent_proto protoreflect.FileDescriptor

const file_intent_proto_rawDesc = "" +
	"\n" +
	"\fintent.proto\x12\vkaboomproto\x1a\n" +
	"move.proto\x1a\x0eposition.proto\"\x86\x02\n" +
	"\x06Intent\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12,\n" +
	"\x12acting_player_uuid\x18\x02 \x01(\tR\x10actingPlayerUuid\x12<\n" +
	"\n" +
	"piece_move\x18\n" +
	" \x01(\v2\x1d.kaboomproto.Intent_PieceMoveR\tpieceMove\x12H\n" +
	"\x0epiece_transfer\x18\v \x01(\v2!.kaboomproto.Intent_PieceTransferR\rpieceTransfer\x122\n" +
	"\x06resign\x18\f \x01(\v2\x1a.kaboomproto.Intent_ResignR\x06resign\"^\n" +
	"\x10Intent_PieceMove\x12\x1d\n" +
	"\n" +
	"board_uuid\x18\x01 \x01(\tR\tboardUuid\x12+\n" +
	"\x04move\x18\x02 \x01(\v2\x17.kaboomproto.KaboomMoveR\x04move\"\xc1\x01\n" +
	"\x14Intent_PieceTransfer\x12\x1d\n" +
	"\n" +
	"piece_uuid\x18\x01 \x01(\tR\tpieceUuid\x12\"\n" +
	"\rto_board_uuid\x18\x02 \x01(\tR\vtoBoardUuid\x12.\n" +
	"\ato_zone\x18\x03 \x01(\x0e2\x15.kaboomproto.ZoneKindR\x06toZone\x126\n" +
	"\vto_position\x18\x04 \x01(\v2\x15.kaboomproto.PositionR\n" +
	"toPosition\"F\n" +
	"\rIntent_Resign\x12\x1d\n" +
	"\n" +
	"board_uuid\x18\x01 \x01(\tR\tboardUuid\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reasonB1Z/github.com/fsufitch/kaboom/proto/go;kaboomprotob\x06proto3"

var (
	file_intent_proto_rawDescOnce sync.Once
	file_intent_proto_rawDescData []byte
)

func file_intent_proto_rawDescGZIP() []byte {
	file_intent_proto_rawDescOnce.Do(func() {
		file_intent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_intent_proto_rawDesc), len(file_intent_proto_rawDesc)))
	})
	return file_intent_proto_rawDescData
}

var file_intent_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_intent_proto_goTypes = []any{
	(*Intent)(nil),               // 0: kaboomproto.Intent
	(*Intent_PieceMove)(nil),     // 1: kaboomproto.Intent_PieceMove
	(*Intent_PieceTransfer)(nil), // 2: kaboomproto.Intent_PieceTransfer
	(*Intent_Resign)(nil),        // 3: kaboomproto.Intent_Resign
	(*KaboomMove)(nil),           // 4: kaboomproto.KaboomMove
	(ZoneKind)(0),                // 5: kaboomproto.ZoneKind
	(*Position)(nil),             // 6: kaboomproto.Position
}
var file_intent_proto_depIdxs = []int32{
	1, // 0: kaboomproto.Intent.piece_move:type_name -> kaboomproto.Intent_PieceMove
	2, // 1: kaboomproto.Intent.piece_transfer:type_name -> kaboomproto.Intent_PieceTransfer
	3, // 2: kaboomproto.Intent.resign:type_name -> kaboomproto.Intent_Resign
	4, // 3: kaboomproto.Intent_PieceMove.move:type_name -> kaboomproto.KaboomMove
	5, // 4: kaboomproto.Intent_PieceTransfer.to_zone:type_name -> kaboomproto.ZoneKind
	6, // 5: kaboomproto.Intent_PieceTransfer.to_position:type_name -> kaboomproto.Position
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_intent_proto_init() }
func file_intent_proto_init() {
	if File_intent_proto != nil {
		return
	}
	file_move_proto_init()
	file_position_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_intent_proto_rawDesc), len(file_intent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_intent_proto_goTypes,
		DependencyIndexes: file_intent_proto_depIdxs,
		MessageInfos:      file_intent_proto_msgTypes,
	}.Build()
	File_intent_proto = out.File
	file_intent_proto_goTypes = nil
	file_intent_proto_depIdxs = nil
}
