// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: location.proto

package kaboomproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ZoneKind represents different zones on a board a piece can be in.
type ZoneKind int32

const (
	ZoneKind_ZONE_INVALID   ZoneKind = 0
	ZoneKind_ZONE_BOARD     ZoneKind = 1 // On the main chess board
	ZoneKind_ZONE_GRAVEYARD ZoneKind = 2 // Captured
	ZoneKind_ZONE_BENCH     ZoneKind = 3 // Ready to be deployed
	ZoneKind_ZONE_TEMPORARY ZoneKind = 4 // For transient states
)

// Enum value maps for ZoneKind.
var (
	ZoneKind_name = map[int32]string{
		0: "ZONE_INVALID",
		1: "ZONE_BOARD",
		2: "ZONE_GRAVEYARD",
		3: "ZONE_BENCH",
		4: "ZONE_TEMPORARY",
	}
	ZoneKind_value = map[string]int32{
		"ZONE_INVALID":   0,
		"ZONE_BOARD":     1,
		"ZONE_GRAVEYARD": 2,
		"ZONE_BENCH":     3,
		"ZONE_TEMPORARY": 4,
	}
)

func (x ZoneKind) Enum() *ZoneKind {
	p := new(ZoneKind)
	*p = x
	return p
}

func (x ZoneKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ZoneKind) Descriptor() protoreflect.EnumDescriptor {
	return file_location_proto_enumTypes[0].Descriptor()
}

func (ZoneKind) Type() protoreflect.EnumType {
	return &file_location_proto_enumTypes[0]
}

func (x ZoneKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ZoneKind.Descriptor instead.
func (ZoneKind) EnumDescriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{0}
}

// Location fully describes a specific location in a game, including board, zone, and position.
type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardUuid     string                 `protobuf:"bytes,1,opt,name=board_uuid,json=boardUuid,proto3" json:"board_uuid,omitempty"`
	Zone          ZoneKind               `protobuf:"varint,2,opt,name=zone,proto3,enum=kaboomproto.ZoneKind" json:"zone,omitempty"`
	Row           int64                  `protobuf:"varint,3,opt,name=row,proto3" json:"row,omitempty"`
	Col           int64                  `protobuf:"varint,4,opt,name=col,proto3" json:"col,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetBoardUuid() string {
	if x != nil {
		return x.BoardUuid
	}
	return ""
}

func (x *Location) GetZone() ZoneKind {
	if x != nil {
		return x.Zone
	}
	return ZoneKind_ZONE_INVALID
}

func (x *Location) GetRow() int64 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *Location) GetCol() int64 {
	if x != nil {
		return x.Col
	}
	return 0
}

// LocationVector represents a movement from one Location to another.
type LocationVector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *Location              `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            *Location              `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationVector) Reset() {
	*x = LocationVector{}
	mi := &file_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationVector) ProtoMessage() {}

func (x *LocationVector) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationVector.ProtoReflect.Descriptor instead.
func (*LocationVector) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{1}
}

func (x *LocationVector) GetFrom() *Location {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *LocationVector) GetTo() *Location {
	if x != nil {
		return x.To
	}
	return nil
}

var File_location_proto protoreflect.FileDescriptor

const file_location_proto_rawDesc = "" +
	"\n" +
	"\x0elocation.proto\x12\vkaboomproto\"x\n" +
	"\bLocation\x12\x1d\n" +
	"\n" +
	"board_uuid\x18\x01 \x01(\tR\tboardUuid\x12)\n" +
	"\x04zone\x18\x02 \x01(\x0e2\x15.kaboomproto.ZoneKindR\x04zone\x12\x10\n" +
	"\x03row\x18\x03 \x01(\x03R\x03row\x12\x10\n" +
	"\x03col\x18\x04 \x01(\x03R\x03col\"b\n" +
	"\x0eLocationVector\x12)\n" +
	"\x04from\x18\x01 \x01(\v2\x15.kaboomproto.LocationR\x04from\x12%\n" +
	"\x02to\x18\x02 \x01(\v2\x15.kaboomproto.LocationR\x02to*d\n" +
	"\bZoneKind\x12\x10\n" +
	"\fZONE_INVALID\x10\x00\x12\x0e\n" +
	"\n" +
	"ZONE_BOARD\x10\x01\x12\x12\n" +
	"\x0eZONE_GRAVEYARD\x10\x02\x12\x0e\n" +
	"\n" +
	"ZONE_BENCH\x10\x03\x12\x12\n" +
	"\x0eZONE_TEMPORARY\x10\x04B1Z/github.com/fsufitch/kaboom/proto/go;kaboomprotob\x06proto3"

var (
	file_location_proto_rawDescOnce sync.Once
	file_location_proto_rawDescData []byte
)

func file_location_proto_rawDescGZIP() []byte {
	file_location_proto_rawDescOnce.Do(func() {
		file_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_location_proto_rawDesc), len(file_location_proto_rawDesc)))
	})
	return file_location_proto_rawDescData
}

var file_location_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_location_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_location_proto_goTypes = []any{
	(ZoneKind)(0),          // 0: kaboomproto.ZoneKind
	(*Location)(nil),       // 1: kaboomproto.Location
	(*LocationVector)(nil), // 2: kaboomproto.LocationVector
}
var file_location_proto_depIdxs = []int32{
	0, // 0: kaboomproto.Location.zone:type_name -> kaboomproto.ZoneKind
	1, // 1: kaboomproto.LocationVector.from:type_name -> kaboomproto.Location
	1, // 2: kaboomproto.LocationVector.to:type_name -> kaboomproto.Location
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_location_proto_init() }
func file_location_proto_init() {
	if File_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_location_proto_rawDesc), len(file_location_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_location_proto_goTypes,
		DependencyIndexes: file_location_proto_depIdxs,
		EnumInfos:         file_location_proto_enumTypes,
		MessageInfos:      file_location_proto_msgTypes,
	}.Build()
	File_location_proto = out.File
	file_location_proto_goTypes = nil
	file_location_proto_depIdxs = nil
}
