// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: move_classic.proto

package kaboomproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PawnMove is a normal pawn move in regular chess rules.
// It encompasses single and double square advances.
type PawnMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        *LocationVector        `protobuf:"bytes,1,opt,name=vector,proto3" json:"vector,omitempty"`
	Promotion     PieceKind              `protobuf:"varint,10,opt,name=promotion,proto3,enum=kaboomproto.PieceKind" json:"promotion,omitempty"` // optional promotion piece type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PawnMove) Reset() {
	*x = PawnMove{}
	mi := &file_move_classic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PawnMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PawnMove) ProtoMessage() {}

func (x *PawnMove) ProtoReflect() protoreflect.Message {
	mi := &file_move_classic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PawnMove.ProtoReflect.Descriptor instead.
func (*PawnMove) Descriptor() ([]byte, []int) {
	return file_move_classic_proto_rawDescGZIP(), []int{0}
}

func (x *PawnMove) GetVector() *LocationVector {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *PawnMove) GetPromotion() PieceKind {
	if x != nil {
		return x.Promotion
	}
	return PieceKind_INVALID_PIECE
}

// PawnCapture is a normal pawn capture move in regular chess rules.
// It encompasses regular and en passant captures.
type PawnCapture struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        *LocationVector        `protobuf:"bytes,1,opt,name=vector,proto3" json:"vector,omitempty"`
	Promotion     PieceKind              `protobuf:"varint,10,opt,name=promotion,proto3,enum=kaboomproto.PieceKind" json:"promotion,omitempty"` // optional promotion piece type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PawnCapture) Reset() {
	*x = PawnCapture{}
	mi := &file_move_classic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PawnCapture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PawnCapture) ProtoMessage() {}

func (x *PawnCapture) ProtoReflect() protoreflect.Message {
	mi := &file_move_classic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PawnCapture.ProtoReflect.Descriptor instead.
func (*PawnCapture) Descriptor() ([]byte, []int) {
	return file_move_classic_proto_rawDescGZIP(), []int{1}
}

func (x *PawnCapture) GetVector() *LocationVector {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *PawnCapture) GetPromotion() PieceKind {
	if x != nil {
		return x.Promotion
	}
	return PieceKind_INVALID_PIECE
}

// KnightMove is a normal knight move in regular chess rules.
type KnightMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        *LocationVector        `protobuf:"bytes,1,opt,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnightMove) Reset() {
	*x = KnightMove{}
	mi := &file_move_classic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnightMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnightMove) ProtoMessage() {}

func (x *KnightMove) ProtoReflect() protoreflect.Message {
	mi := &file_move_classic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnightMove.ProtoReflect.Descriptor instead.
func (*KnightMove) Descriptor() ([]byte, []int) {
	return file_move_classic_proto_rawDescGZIP(), []int{2}
}

func (x *KnightMove) GetVector() *LocationVector {
	if x != nil {
		return x.Vector
	}
	return nil
}

// KnightCapture is a normal knight capture move in regular chess rules.
type KnightCapture struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        *LocationVector        `protobuf:"bytes,1,opt,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnightCapture) Reset() {
	*x = KnightCapture{}
	mi := &file_move_classic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnightCapture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnightCapture) ProtoMessage() {}

func (x *KnightCapture) ProtoReflect() protoreflect.Message {
	mi := &file_move_classic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnightCapture.ProtoReflect.Descriptor instead.
func (*KnightCapture) Descriptor() ([]byte, []int) {
	return file_move_classic_proto_rawDescGZIP(), []int{3}
}

func (x *KnightCapture) GetVector() *LocationVector {
	if x != nil {
		return x.Vector
	}
	return nil
}

// BishopMove is a normal bishop move in regular chess rules.
type BishopMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        *LocationVector        `protobuf:"bytes,1,opt,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BishopMove) Reset() {
	*x = BishopMove{}
	mi := &file_move_classic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BishopMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BishopMove) ProtoMessage() {}

func (x *BishopMove) ProtoReflect() protoreflect.Message {
	mi := &file_move_classic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BishopMove.ProtoReflect.Descriptor instead.
func (*BishopMove) Descriptor() ([]byte, []int) {
	return file_move_classic_proto_rawDescGZIP(), []int{4}
}

func (x *BishopMove) GetVector() *LocationVector {
	if x != nil {
		return x.Vector
	}
	return nil
}

// BishopCapture is a normal bishop capture move in regular chess rules.
type BishopCapture struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        *LocationVector        `protobuf:"bytes,1,opt,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BishopCapture) Reset() {
	*x = BishopCapture{}
	mi := &file_move_classic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BishopCapture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BishopCapture) ProtoMessage() {}

func (x *BishopCapture) ProtoReflect() protoreflect.Message {
	mi := &file_move_classic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BishopCapture.ProtoReflect.Descriptor instead.
func (*BishopCapture) Descriptor() ([]byte, []int) {
	return file_move_classic_proto_rawDescGZIP(), []int{5}
}

func (x *BishopCapture) GetVector() *LocationVector {
	if x != nil {
		return x.Vector
	}
	return nil
}

// RookMove is a normal rook move in regular chess rules.
type RookMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        *LocationVector        `protobuf:"bytes,1,opt,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RookMove) Reset() {
	*x = RookMove{}
	mi := &file_move_classic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RookMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RookMove) ProtoMessage() {}

func (x *RookMove) ProtoReflect() protoreflect.Message {
	mi := &file_move_classic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RookMove.ProtoReflect.Descriptor instead.
func (*RookMove) Descriptor() ([]byte, []int) {
	return file_move_classic_proto_rawDescGZIP(), []int{6}
}

func (x *RookMove) GetVector() *LocationVector {
	if x != nil {
		return x.Vector
	}
	return nil
}

// RookCapture is a normal rook capture move in regular chess rules.
type RookCapture struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        *LocationVector        `protobuf:"bytes,1,opt,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RookCapture) Reset() {
	*x = RookCapture{}
	mi := &file_move_classic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RookCapture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RookCapture) ProtoMessage() {}

func (x *RookCapture) ProtoReflect() protoreflect.Message {
	mi := &file_move_classic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RookCapture.ProtoReflect.Descriptor instead.
func (*RookCapture) Descriptor() ([]byte, []int) {
	return file_move_classic_proto_rawDescGZIP(), []int{7}
}

func (x *RookCapture) GetVector() *LocationVector {
	if x != nil {
		return x.Vector
	}
	return nil
}

// QueenMove is a normal queen move in regular chess rules.
type QueenMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        *LocationVector        `protobuf:"bytes,1,opt,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueenMove) Reset() {
	*x = QueenMove{}
	mi := &file_move_classic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueenMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueenMove) ProtoMessage() {}

func (x *QueenMove) ProtoReflect() protoreflect.Message {
	mi := &file_move_classic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueenMove.ProtoReflect.Descriptor instead.
func (*QueenMove) Descriptor() ([]byte, []int) {
	return file_move_classic_proto_rawDescGZIP(), []int{8}
}

func (x *QueenMove) GetVector() *LocationVector {
	if x != nil {
		return x.Vector
	}
	return nil
}

// QueenCapture is a normal queen capture move in regular chess rules.
type QueenCapture struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        *LocationVector        `protobuf:"bytes,1,opt,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueenCapture) Reset() {
	*x = QueenCapture{}
	mi := &file_move_classic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueenCapture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueenCapture) ProtoMessage() {}

func (x *QueenCapture) ProtoReflect() protoreflect.Message {
	mi := &file_move_classic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueenCapture.ProtoReflect.Descriptor instead.
func (*QueenCapture) Descriptor() ([]byte, []int) {
	return file_move_classic_proto_rawDescGZIP(), []int{9}
}

func (x *QueenCapture) GetVector() *LocationVector {
	if x != nil {
		return x.Vector
	}
	return nil
}

// KingMove is a normal king move in regular chess rules.
type KingMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        *LocationVector        `protobuf:"bytes,1,opt,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KingMove) Reset() {
	*x = KingMove{}
	mi := &file_move_classic_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KingMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KingMove) ProtoMessage() {}

func (x *KingMove) ProtoReflect() protoreflect.Message {
	mi := &file_move_classic_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KingMove.ProtoReflect.Descriptor instead.
func (*KingMove) Descriptor() ([]byte, []int) {
	return file_move_classic_proto_rawDescGZIP(), []int{10}
}

func (x *KingMove) GetVector() *LocationVector {
	if x != nil {
		return x.Vector
	}
	return nil
}

// KingCapture is a normal king capture move in regular chess rules.
type KingCapture struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        *LocationVector        `protobuf:"bytes,1,opt,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KingCapture) Reset() {
	*x = KingCapture{}
	mi := &file_move_classic_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KingCapture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KingCapture) ProtoMessage() {}

func (x *KingCapture) ProtoReflect() protoreflect.Message {
	mi := &file_move_classic_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KingCapture.ProtoReflect.Descriptor instead.
func (*KingCapture) Descriptor() ([]byte, []int) {
	return file_move_classic_proto_rawDescGZIP(), []int{11}
}

func (x *KingCapture) GetVector() *LocationVector {
	if x != nil {
		return x.Vector
	}
	return nil
}

// KingCastle is a normal king castling move in regular chess rules.
type KingCastle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KingVector    *LocationVector        `protobuf:"bytes,1,opt,name=king_vector,json=kingVector,proto3" json:"king_vector,omitempty"`
	RookVector    *LocationVector        `protobuf:"bytes,2,opt,name=rook_vector,json=rookVector,proto3" json:"rook_vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KingCastle) Reset() {
	*x = KingCastle{}
	mi := &file_move_classic_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KingCastle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KingCastle) ProtoMessage() {}

func (x *KingCastle) ProtoReflect() protoreflect.Message {
	mi := &file_move_classic_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KingCastle.ProtoReflect.Descriptor instead.
func (*KingCastle) Descriptor() ([]byte, []int) {
	return file_move_classic_proto_rawDescGZIP(), []int{12}
}

func (x *KingCastle) GetKingVector() *LocationVector {
	if x != nil {
		return x.KingVector
	}
	return nil
}

func (x *KingCastle) GetRookVector() *LocationVector {
	if x != nil {
		return x.RookVector
	}
	return nil
}

// Resign is a "move" indicating that the player resigns the game.
type Resign struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resign) Reset() {
	*x = Resign{}
	mi := &file_move_classic_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resign) ProtoMessage() {}

func (x *Resign) ProtoReflect() protoreflect.Message {
	mi := &file_move_classic_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resign.ProtoReflect.Descriptor instead.
func (*Resign) Descriptor() ([]byte, []int) {
	return file_move_classic_proto_rawDescGZIP(), []int{13}
}

var File_move_classic_proto protoreflect.FileDescriptor

const file_move_classic_proto_rawDesc = "" +
	"\n" +
	"\x12move_classic.proto\x12\vkaboomproto\x1a\x0elocation.proto\x1a\vpiece.proto\"u\n" +
	"\bPawnMove\x123\n" +
	"\x06vector\x18\x01 \x01(\v2\x1b.kaboomproto.LocationVectorR\x06vector\x124\n" +
	"\tpromotion\x18\n" +
	" \x01(\x0e2\x16.kaboomproto.PieceKindR\tpromotion\"x\n" +
	"\vPawnCapture\x123\n" +
	"\x06vector\x18\x01 \x01(\v2\x1b.kaboomproto.LocationVectorR\x06vector\x124\n" +
	"\tpromotion\x18\n" +
	" \x01(\x0e2\x16.kaboomproto.PieceKindR\tpromotion\"A\n" +
	"\n" +
	"KnightMove\x123\n" +
	"\x06vector\x18\x01 \x01(\v2\x1b.kaboomproto.LocationVectorR\x06vector\"D\n" +
	"\rKnightCapture\x123\n" +
	"\x06vector\x18\x01 \x01(\v2\x1b.kaboomproto.LocationVectorR\x06vector\"A\n" +
	"\n" +
	"BishopMove\x123\n" +
	"\x06vector\x18\x01 \x01(\v2\x1b.kaboomproto.LocationVectorR\x06vector\"D\n" +
	"\rBishopCapture\x123\n" +
	"\x06vector\x18\x01 \x01(\v2\x1b.kaboomproto.LocationVectorR\x06vector\"?\n" +
	"\bRookMove\x123\n" +
	"\x06vector\x18\x01 \x01(\v2\x1b.kaboomproto.LocationVectorR\x06vector\"B\n" +
	"\vRookCapture\x123\n" +
	"\x06vector\x18\x01 \x01(\v2\x1b.kaboomproto.LocationVectorR\x06vector\"@\n" +
	"\tQueenMove\x123\n" +
	"\x06vector\x18\x01 \x01(\v2\x1b.kaboomproto.LocationVectorR\x06vector\"C\n" +
	"\fQueenCapture\x123\n" +
	"\x06vector\x18\x01 \x01(\v2\x1b.kaboomproto.LocationVectorR\x06vector\"?\n" +
	"\bKingMove\x123\n" +
	"\x06vector\x18\x01 \x01(\v2\x1b.kaboomproto.LocationVectorR\x06vector\"B\n" +
	"\vKingCapture\x123\n" +
	"\x06vector\x18\x01 \x01(\v2\x1b.kaboomproto.LocationVectorR\x06vector\"\x88\x01\n" +
	"\n" +
	"KingCastle\x12<\n" +
	"\vking_vector\x18\x01 \x01(\v2\x1b.kaboomproto.LocationVectorR\n" +
	"kingVector\x12<\n" +
	"\vrook_vector\x18\x02 \x01(\v2\x1b.kaboomproto.LocationVectorR\n" +
	"rookVector\"\b\n" +
	"\x06ResignB1Z/github.com/fsufitch/kaboom/proto/go;kaboomprotob\x06proto3"

var (
	file_move_classic_proto_rawDescOnce sync.Once
	file_move_classic_proto_rawDescData []byte
)

func file_move_classic_proto_rawDescGZIP() []byte {
	file_move_classic_proto_rawDescOnce.Do(func() {
		file_move_classic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_move_classic_proto_rawDesc), len(file_move_classic_proto_rawDesc)))
	})
	return file_move_classic_proto_rawDescData
}

var file_move_classic_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_move_classic_proto_goTypes = []any{
	(*PawnMove)(nil),       // 0: kaboomproto.PawnMove
	(*PawnCapture)(nil),    // 1: kaboomproto.PawnCapture
	(*KnightMove)(nil),     // 2: kaboomproto.KnightMove
	(*KnightCapture)(nil),  // 3: kaboomproto.KnightCapture
	(*BishopMove)(nil),     // 4: kaboomproto.BishopMove
	(*BishopCapture)(nil),  // 5: kaboomproto.BishopCapture
	(*RookMove)(nil),       // 6: kaboomproto.RookMove
	(*RookCapture)(nil),    // 7: kaboomproto.RookCapture
	(*QueenMove)(nil),      // 8: kaboomproto.QueenMove
	(*QueenCapture)(nil),   // 9: kaboomproto.QueenCapture
	(*KingMove)(nil),       // 10: kaboomproto.KingMove
	(*KingCapture)(nil),    // 11: kaboomproto.KingCapture
	(*KingCastle)(nil),     // 12: kaboomproto.KingCastle
	(*Resign)(nil),         // 13: kaboomproto.Resign
	(*LocationVector)(nil), // 14: kaboomproto.LocationVector
	(PieceKind)(0),         // 15: kaboomproto.PieceKind
}
var file_move_classic_proto_depIdxs = []int32{
	14, // 0: kaboomproto.PawnMove.vector:type_name -> kaboomproto.LocationVector
	15, // 1: kaboomproto.PawnMove.promotion:type_name -> kaboomproto.PieceKind
	14, // 2: kaboomproto.PawnCapture.vector:type_name -> kaboomproto.LocationVector
	15, // 3: kaboomproto.PawnCapture.promotion:type_name -> kaboomproto.PieceKind
	14, // 4: kaboomproto.KnightMove.vector:type_name -> kaboomproto.LocationVector
	14, // 5: kaboomproto.KnightCapture.vector:type_name -> kaboomproto.LocationVector
	14, // 6: kaboomproto.BishopMove.vector:type_name -> kaboomproto.LocationVector
	14, // 7: kaboomproto.BishopCapture.vector:type_name -> kaboomproto.LocationVector
	14, // 8: kaboomproto.RookMove.vector:type_name -> kaboomproto.LocationVector
	14, // 9: kaboomproto.RookCapture.vector:type_name -> kaboomproto.LocationVector
	14, // 10: kaboomproto.QueenMove.vector:type_name -> kaboomproto.LocationVector
	14, // 11: kaboomproto.QueenCapture.vector:type_name -> kaboomproto.LocationVector
	14, // 12: kaboomproto.KingMove.vector:type_name -> kaboomproto.LocationVector
	14, // 13: kaboomproto.KingCapture.vector:type_name -> kaboomproto.LocationVector
	14, // 14: kaboomproto.KingCastle.king_vector:type_name -> kaboomproto.LocationVector
	14, // 15: kaboomproto.KingCastle.rook_vector:type_name -> kaboomproto.LocationVector
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_move_classic_proto_init() }
func file_move_classic_proto_init() {
	if File_move_classic_proto != nil {
		return
	}
	file_location_proto_init()
	file_piece_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_move_classic_proto_rawDesc), len(file_move_classic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_move_classic_proto_goTypes,
		DependencyIndexes: file_move_classic_proto_depIdxs,
		MessageInfos:      file_move_classic_proto_msgTypes,
	}.Build()
	File_move_classic_proto = out.File
	file_move_classic_proto_goTypes = nil
	file_move_classic_proto_depIdxs = nil
}
