// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: move.proto

package kaboomproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KaboomMove struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Move:
	//
	//	*KaboomMove_PawnMove
	//	*KaboomMove_PawnCapture
	//	*KaboomMove_PawnBump
	//	*KaboomMove_PawnExplosion
	//	*KaboomMove_KnightMove
	//	*KaboomMove_KnightCapture
	//	*KaboomMove_KnightBump
	//	*KaboomMove_KnightStomp
	//	*KaboomMove_BishopMove
	//	*KaboomMove_BishopCapture
	//	*KaboomMove_BishopBump
	//	*KaboomMove_BishopSnipe
	//	*KaboomMove_Roomove
	//	*KaboomMove_Roocapture
	//	*KaboomMove_Roobump
	//	*KaboomMove_Rootackle
	//	*KaboomMove_QueenMove
	//	*KaboomMove_QueenCapture
	//	*KaboomMove_QueenBump
	//	*KaboomMove_QueenNova
	//	*KaboomMove_KingMove
	//	*KaboomMove_KingCapture
	//	*KaboomMove_KingBump
	//	*KaboomMove_KingControl
	//	*KaboomMove_KingCastle
	//	*KaboomMove_Resign
	//	*KaboomMove_DeployPiece
	Move          isKaboomMove_Move `protobuf_oneof:"move"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KaboomMove) Reset() {
	*x = KaboomMove{}
	mi := &file_move_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KaboomMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KaboomMove) ProtoMessage() {}

func (x *KaboomMove) ProtoReflect() protoreflect.Message {
	mi := &file_move_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KaboomMove.ProtoReflect.Descriptor instead.
func (*KaboomMove) Descriptor() ([]byte, []int) {
	return file_move_proto_rawDescGZIP(), []int{0}
}

func (x *KaboomMove) GetMove() isKaboomMove_Move {
	if x != nil {
		return x.Move
	}
	return nil
}

func (x *KaboomMove) GetPawnMove() *PawnMove {
	if x != nil {
		if x, ok := x.Move.(*KaboomMove_PawnMove); ok {
			return x.PawnMove
		}
	}
	return nil
}

func (x *KaboomMove) GetPawnCapture() *PawnCapture {
	if x != nil {
		if x, ok := x.Move.(*KaboomMove_PawnCapture); ok {
			return x.PawnCapture
		}
	}
	return nil
}

func (x *KaboomMove) GetPawnBump() *PawnBump {
	if x != nil {
		if x, ok := x.Move.(*KaboomMove_PawnBump); ok {
			return x.PawnBump
		}
	}
	return nil
}

func (x *KaboomMove) GetPawnExplosion() *PawnExplosion {
	if x != nil {
		if x, ok := x.Move.(*KaboomMove_PawnExplosion); ok {
			return x.PawnExplosion
		}
	}
	return nil
}

func (x *KaboomMove) GetKnightMove() *KnightMove {
	if x != nil {
		if x, ok := x.Move.(*KaboomMove_KnightMove); ok {
			return x.KnightMove
		}
	}
	return nil
}

func (x *KaboomMove) GetKnightCapture() *KnightCapture {
	if x != nil {
		if x, ok := x.Move.(*KaboomMove_KnightCapture); ok {
			return x.KnightCapture
		}
	}
	return nil
}

func (x *KaboomMove) GetKnightBump() *KnightBump {
	if x != nil {
		if x, ok := x.Move.(*KaboomMove_KnightBump); ok {
			return x.KnightBump
		}
	}
	return nil
}

func (x *KaboomMove) GetKnightStomp() *KnightStomp {
	if x != nil {
		if x, ok := x.Move.(*KaboomMove_KnightStomp); ok {
			return x.KnightStomp
		}
	}
	return nil
}

func (x *KaboomMove) GetBishopMove() *BishopMove {
	if x != nil {
		if x, ok := x.Move.(*KaboomMove_BishopMove); ok {
			return x.BishopMove
		}
	}
	return nil
}

func (x *KaboomMove) GetBishopCapture() *BishopCapture {
	if x != nil {
		if x, ok := x.Move.(*KaboomMove_BishopCapture); ok {
			return x.BishopCapture
		}
	}
	return nil
}

func (x *KaboomMove) GetBishopBump() *BishopBump {
	if x != nil {
		if x, ok := x.Move.(*KaboomMove_BishopBump); ok {
			return x.BishopBump
		}
	}
	return nil
}

func (x *KaboomMove) GetBishopSnipe() *BishopSnipe {
	if x != nil {
		if x, ok := x.Move.(*KaboomMove_BishopSnipe); ok {
			return x.BishopSnipe
		}
	}
	return nil
}

func (x *KaboomMove) GetRoomove() *RookMove {
	if x != nil {
		if x, ok := x.Move.(*KaboomMove_Roomove); ok {
			return x.Roomove
		}
	}
	return nil
}

func (x *KaboomMove) GetRoocapture() *RookCapture {
	if x != nil {
		if x, ok := x.Move.(*KaboomMove_Roocapture); ok {
			return x.Roocapture
		}
	}
	return nil
}

func (x *KaboomMove) GetRoobump() *RookBump {
	if x != nil {
		if x, ok := x.Move.(*KaboomMove_Roobump); ok {
			return x.Roobump
		}
	}
	return nil
}

func (x *KaboomMove) GetRootackle() *RookTackle {
	if x != nil {
		if x, ok := x.Move.(*KaboomMove_Rootackle); ok {
			return x.Rootackle
		}
	}
	return nil
}

func (x *KaboomMove) GetQueenMove() *QueenMove {
	if x != nil {
		if x, ok := x.Move.(*KaboomMove_QueenMove); ok {
			return x.QueenMove
		}
	}
	return nil
}

func (x *KaboomMove) GetQueenCapture() *QueenCapture {
	if x != nil {
		if x, ok := x.Move.(*KaboomMove_QueenCapture); ok {
			return x.QueenCapture
		}
	}
	return nil
}

func (x *KaboomMove) GetQueenBump() *QueenBump {
	if x != nil {
		if x, ok := x.Move.(*KaboomMove_QueenBump); ok {
			return x.QueenBump
		}
	}
	return nil
}

func (x *KaboomMove) GetQueenNova() *QueenNova {
	if x != nil {
		if x, ok := x.Move.(*KaboomMove_QueenNova); ok {
			return x.QueenNova
		}
	}
	return nil
}

func (x *KaboomMove) GetKingMove() *KingMove {
	if x != nil {
		if x, ok := x.Move.(*KaboomMove_KingMove); ok {
			return x.KingMove
		}
	}
	return nil
}

func (x *KaboomMove) GetKingCapture() *KingCapture {
	if x != nil {
		if x, ok := x.Move.(*KaboomMove_KingCapture); ok {
			return x.KingCapture
		}
	}
	return nil
}

func (x *KaboomMove) GetKingBump() *KingBump {
	if x != nil {
		if x, ok := x.Move.(*KaboomMove_KingBump); ok {
			return x.KingBump
		}
	}
	return nil
}

func (x *KaboomMove) GetKingControl() *KingControl {
	if x != nil {
		if x, ok := x.Move.(*KaboomMove_KingControl); ok {
			return x.KingControl
		}
	}
	return nil
}

func (x *KaboomMove) GetKingCastle() *KingCastle {
	if x != nil {
		if x, ok := x.Move.(*KaboomMove_KingCastle); ok {
			return x.KingCastle
		}
	}
	return nil
}

func (x *KaboomMove) GetResign() *Resign {
	if x != nil {
		if x, ok := x.Move.(*KaboomMove_Resign); ok {
			return x.Resign
		}
	}
	return nil
}

func (x *KaboomMove) GetDeployPiece() *DeployPiece {
	if x != nil {
		if x, ok := x.Move.(*KaboomMove_DeployPiece); ok {
			return x.DeployPiece
		}
	}
	return nil
}

type isKaboomMove_Move interface {
	isKaboomMove_Move()
}

type KaboomMove_PawnMove struct {
	PawnMove *PawnMove `protobuf:"bytes,10,opt,name=pawn_move,json=pawnMove,proto3,oneof"`
}

type KaboomMove_PawnCapture struct {
	PawnCapture *PawnCapture `protobuf:"bytes,11,opt,name=pawn_capture,json=pawnCapture,proto3,oneof"`
}

type KaboomMove_PawnBump struct {
	PawnBump *PawnBump `protobuf:"bytes,12,opt,name=pawn_bump,json=pawnBump,proto3,oneof"`
}

type KaboomMove_PawnExplosion struct {
	PawnExplosion *PawnExplosion `protobuf:"bytes,13,opt,name=pawn_explosion,json=pawnExplosion,proto3,oneof"`
}

type KaboomMove_KnightMove struct {
	KnightMove *KnightMove `protobuf:"bytes,20,opt,name=knight_move,json=knightMove,proto3,oneof"`
}

type KaboomMove_KnightCapture struct {
	KnightCapture *KnightCapture `protobuf:"bytes,21,opt,name=knight_capture,json=knightCapture,proto3,oneof"`
}

type KaboomMove_KnightBump struct {
	KnightBump *KnightBump `protobuf:"bytes,22,opt,name=knight_bump,json=knightBump,proto3,oneof"`
}

type KaboomMove_KnightStomp struct {
	KnightStomp *KnightStomp `protobuf:"bytes,23,opt,name=knight_stomp,json=knightStomp,proto3,oneof"`
}

type KaboomMove_BishopMove struct {
	BishopMove *BishopMove `protobuf:"bytes,30,opt,name=bishop_move,json=bishopMove,proto3,oneof"`
}

type KaboomMove_BishopCapture struct {
	BishopCapture *BishopCapture `protobuf:"bytes,31,opt,name=bishop_capture,json=bishopCapture,proto3,oneof"`
}

type KaboomMove_BishopBump struct {
	BishopBump *BishopBump `protobuf:"bytes,32,opt,name=bishop_bump,json=bishopBump,proto3,oneof"`
}

type KaboomMove_BishopSnipe struct {
	BishopSnipe *BishopSnipe `protobuf:"bytes,33,opt,name=bishop_snipe,json=bishopSnipe,proto3,oneof"`
}

type KaboomMove_Roomove struct {
	Roomove *RookMove `protobuf:"bytes,40,opt,name=roomove,proto3,oneof"`
}

type KaboomMove_Roocapture struct {
	Roocapture *RookCapture `protobuf:"bytes,41,opt,name=roocapture,proto3,oneof"`
}

type KaboomMove_Roobump struct {
	Roobump *RookBump `protobuf:"bytes,42,opt,name=roobump,proto3,oneof"`
}

type KaboomMove_Rootackle struct {
	Rootackle *RookTackle `protobuf:"bytes,43,opt,name=rootackle,proto3,oneof"`
}

type KaboomMove_QueenMove struct {
	QueenMove *QueenMove `protobuf:"bytes,50,opt,name=queen_move,json=queenMove,proto3,oneof"`
}

type KaboomMove_QueenCapture struct {
	QueenCapture *QueenCapture `protobuf:"bytes,51,opt,name=queen_capture,json=queenCapture,proto3,oneof"`
}

type KaboomMove_QueenBump struct {
	QueenBump *QueenBump `protobuf:"bytes,52,opt,name=queen_bump,json=queenBump,proto3,oneof"`
}

type KaboomMove_QueenNova struct {
	QueenNova *QueenNova `protobuf:"bytes,53,opt,name=queen_nova,json=queenNova,proto3,oneof"`
}

type KaboomMove_KingMove struct {
	KingMove *KingMove `protobuf:"bytes,60,opt,name=king_move,json=kingMove,proto3,oneof"`
}

type KaboomMove_KingCapture struct {
	KingCapture *KingCapture `protobuf:"bytes,61,opt,name=king_capture,json=kingCapture,proto3,oneof"`
}

type KaboomMove_KingBump struct {
	KingBump *KingBump `protobuf:"bytes,62,opt,name=king_bump,json=kingBump,proto3,oneof"`
}

type KaboomMove_KingControl struct {
	KingControl *KingControl `protobuf:"bytes,63,opt,name=king_control,json=kingControl,proto3,oneof"`
}

type KaboomMove_KingCastle struct {
	KingCastle *KingCastle `protobuf:"bytes,64,opt,name=king_castle,json=kingCastle,proto3,oneof"`
}

type KaboomMove_Resign struct {
	Resign *Resign `protobuf:"bytes,70,opt,name=resign,proto3,oneof"`
}

type KaboomMove_DeployPiece struct {
	DeployPiece *DeployPiece `protobuf:"bytes,80,opt,name=deploy_piece,json=deployPiece,proto3,oneof"`
}

func (*KaboomMove_PawnMove) isKaboomMove_Move() {}

func (*KaboomMove_PawnCapture) isKaboomMove_Move() {}

func (*KaboomMove_PawnBump) isKaboomMove_Move() {}

func (*KaboomMove_PawnExplosion) isKaboomMove_Move() {}

func (*KaboomMove_KnightMove) isKaboomMove_Move() {}

func (*KaboomMove_KnightCapture) isKaboomMove_Move() {}

func (*KaboomMove_KnightBump) isKaboomMove_Move() {}

func (*KaboomMove_KnightStomp) isKaboomMove_Move() {}

func (*KaboomMove_BishopMove) isKaboomMove_Move() {}

func (*KaboomMove_BishopCapture) isKaboomMove_Move() {}

func (*KaboomMove_BishopBump) isKaboomMove_Move() {}

func (*KaboomMove_BishopSnipe) isKaboomMove_Move() {}

func (*KaboomMove_Roomove) isKaboomMove_Move() {}

func (*KaboomMove_Roocapture) isKaboomMove_Move() {}

func (*KaboomMove_Roobump) isKaboomMove_Move() {}

func (*KaboomMove_Rootackle) isKaboomMove_Move() {}

func (*KaboomMove_QueenMove) isKaboomMove_Move() {}

func (*KaboomMove_QueenCapture) isKaboomMove_Move() {}

func (*KaboomMove_QueenBump) isKaboomMove_Move() {}

func (*KaboomMove_QueenNova) isKaboomMove_Move() {}

func (*KaboomMove_KingMove) isKaboomMove_Move() {}

func (*KaboomMove_KingCapture) isKaboomMove_Move() {}

func (*KaboomMove_KingBump) isKaboomMove_Move() {}

func (*KaboomMove_KingControl) isKaboomMove_Move() {}

func (*KaboomMove_KingCastle) isKaboomMove_Move() {}

func (*KaboomMove_Resign) isKaboomMove_Move() {}

func (*KaboomMove_DeployPiece) isKaboomMove_Move() {}

// KingControl is a Kaboom-specific move where the king "mind-controls" a piece located within a distance of 2 squares
// (New York distance) from its current position, forcing the target piece to perform any of its valid moves.
// This can affect both friendly and opponent pieces. Queens are immune to mind control.
type KingControl struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	King  *Location              `protobuf:"bytes,1,opt,name=king,proto3" json:"king,omitempty"` // king's current position
	// The move that the target piece will perform as a result of mind control.
	ControlMove   *KaboomMove `protobuf:"bytes,3,opt,name=control_move,json=controlMove,proto3" json:"control_move,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KingControl) Reset() {
	*x = KingControl{}
	mi := &file_move_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KingControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KingControl) ProtoMessage() {}

func (x *KingControl) ProtoReflect() protoreflect.Message {
	mi := &file_move_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KingControl.ProtoReflect.Descriptor instead.
func (*KingControl) Descriptor() ([]byte, []int) {
	return file_move_proto_rawDescGZIP(), []int{1}
}

func (x *KingControl) GetKing() *Location {
	if x != nil {
		return x.King
	}
	return nil
}

func (x *KingControl) GetControlMove() *KaboomMove {
	if x != nil {
		return x.ControlMove
	}
	return nil
}

var File_move_proto protoreflect.FileDescriptor

const file_move_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"move.proto\x12\vkaboomproto\x1a\x0elocation.proto\x1a\x12move_classic.proto\x1a\x11move_kaboom.proto\"\xd8\f\n" +
	"\n" +
	"KaboomMove\x124\n" +
	"\tpawn_move\x18\n" +
	" \x01(\v2\x15.kaboomproto.PawnMoveH\x00R\bpawnMove\x12=\n" +
	"\fpawn_capture\x18\v \x01(\v2\x18.kaboomproto.PawnCaptureH\x00R\vpawnCapture\x124\n" +
	"\tpawn_bump\x18\f \x01(\v2\x15.kaboomproto.PawnBumpH\x00R\bpawnBump\x12C\n" +
	"\x0epawn_explosion\x18\r \x01(\v2\x1a.kaboomproto.PawnExplosionH\x00R\rpawnExplosion\x12:\n" +
	"\vknight_move\x18\x14 \x01(\v2\x17.kaboomproto.KnightMoveH\x00R\n" +
	"knightMove\x12C\n" +
	"\x0eknight_capture\x18\x15 \x01(\v2\x1a.kaboomproto.KnightCaptureH\x00R\rknightCapture\x12:\n" +
	"\vknight_bump\x18\x16 \x01(\v2\x17.kaboomproto.KnightBumpH\x00R\n" +
	"knightBump\x12=\n" +
	"\fknight_stomp\x18\x17 \x01(\v2\x18.kaboomproto.KnightStompH\x00R\vknightStomp\x12:\n" +
	"\vbishop_move\x18\x1e \x01(\v2\x17.kaboomproto.BishopMoveH\x00R\n" +
	"bishopMove\x12C\n" +
	"\x0ebishop_capture\x18\x1f \x01(\v2\x1a.kaboomproto.BishopCaptureH\x00R\rbishopCapture\x12:\n" +
	"\vbishop_bump\x18  \x01(\v2\x17.kaboomproto.BishopBumpH\x00R\n" +
	"bishopBump\x12=\n" +
	"\fbishop_snipe\x18! \x01(\v2\x18.kaboomproto.BishopSnipeH\x00R\vbishopSnipe\x121\n" +
	"\aroomove\x18( \x01(\v2\x15.kaboomproto.RookMoveH\x00R\aroomove\x12:\n" +
	"\n" +
	"roocapture\x18) \x01(\v2\x18.kaboomproto.RookCaptureH\x00R\n" +
	"roocapture\x121\n" +
	"\aroobump\x18* \x01(\v2\x15.kaboomproto.RookBumpH\x00R\aroobump\x127\n" +
	"\trootackle\x18+ \x01(\v2\x17.kaboomproto.RookTackleH\x00R\trootackle\x127\n" +
	"\n" +
	"queen_move\x182 \x01(\v2\x16.kaboomproto.QueenMoveH\x00R\tqueenMove\x12@\n" +
	"\rqueen_capture\x183 \x01(\v2\x19.kaboomproto.QueenCaptureH\x00R\fqueenCapture\x127\n" +
	"\n" +
	"queen_bump\x184 \x01(\v2\x16.kaboomproto.QueenBumpH\x00R\tqueenBump\x127\n" +
	"\n" +
	"queen_nova\x185 \x01(\v2\x16.kaboomproto.QueenNovaH\x00R\tqueenNova\x124\n" +
	"\tking_move\x18< \x01(\v2\x15.kaboomproto.KingMoveH\x00R\bkingMove\x12=\n" +
	"\fking_capture\x18= \x01(\v2\x18.kaboomproto.KingCaptureH\x00R\vkingCapture\x124\n" +
	"\tking_bump\x18> \x01(\v2\x15.kaboomproto.KingBumpH\x00R\bkingBump\x12=\n" +
	"\fking_control\x18? \x01(\v2\x18.kaboomproto.KingControlH\x00R\vkingControl\x12:\n" +
	"\vking_castle\x18@ \x01(\v2\x17.kaboomproto.KingCastleH\x00R\n" +
	"kingCastle\x12-\n" +
	"\x06resign\x18F \x01(\v2\x13.kaboomproto.ResignH\x00R\x06resign\x12=\n" +
	"\fdeploy_piece\x18P \x01(\v2\x18.kaboomproto.DeployPieceH\x00R\vdeployPieceB\x06\n" +
	"\x04move\"t\n" +
	"\vKingControl\x12)\n" +
	"\x04king\x18\x01 \x01(\v2\x15.kaboomproto.LocationR\x04king\x12:\n" +
	"\fcontrol_move\x18\x03 \x01(\v2\x17.kaboomproto.KaboomMoveR\vcontrolMoveB1Z/github.com/fsufitch/kaboom/proto/go;kaboomprotob\x06proto3"

var (
	file_move_proto_rawDescOnce sync.Once
	file_move_proto_rawDescData []byte
)

func file_move_proto_rawDescGZIP() []byte {
	file_move_proto_rawDescOnce.Do(func() {
		file_move_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_move_proto_rawDesc), len(file_move_proto_rawDesc)))
	})
	return file_move_proto_rawDescData
}

var file_move_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_move_proto_goTypes = []any{
	(*KaboomMove)(nil),    // 0: kaboomproto.KaboomMove
	(*KingControl)(nil),   // 1: kaboomproto.KingControl
	(*PawnMove)(nil),      // 2: kaboomproto.PawnMove
	(*PawnCapture)(nil),   // 3: kaboomproto.PawnCapture
	(*PawnBump)(nil),      // 4: kaboomproto.PawnBump
	(*PawnExplosion)(nil), // 5: kaboomproto.PawnExplosion
	(*KnightMove)(nil),    // 6: kaboomproto.KnightMove
	(*KnightCapture)(nil), // 7: kaboomproto.KnightCapture
	(*KnightBump)(nil),    // 8: kaboomproto.KnightBump
	(*KnightStomp)(nil),   // 9: kaboomproto.KnightStomp
	(*BishopMove)(nil),    // 10: kaboomproto.BishopMove
	(*BishopCapture)(nil), // 11: kaboomproto.BishopCapture
	(*BishopBump)(nil),    // 12: kaboomproto.BishopBump
	(*BishopSnipe)(nil),   // 13: kaboomproto.BishopSnipe
	(*RookMove)(nil),      // 14: kaboomproto.RookMove
	(*RookCapture)(nil),   // 15: kaboomproto.RookCapture
	(*RookBump)(nil),      // 16: kaboomproto.RookBump
	(*RookTackle)(nil),    // 17: kaboomproto.RookTackle
	(*QueenMove)(nil),     // 18: kaboomproto.QueenMove
	(*QueenCapture)(nil),  // 19: kaboomproto.QueenCapture
	(*QueenBump)(nil),     // 20: kaboomproto.QueenBump
	(*QueenNova)(nil),     // 21: kaboomproto.QueenNova
	(*KingMove)(nil),      // 22: kaboomproto.KingMove
	(*KingCapture)(nil),   // 23: kaboomproto.KingCapture
	(*KingBump)(nil),      // 24: kaboomproto.KingBump
	(*KingCastle)(nil),    // 25: kaboomproto.KingCastle
	(*Resign)(nil),        // 26: kaboomproto.Resign
	(*DeployPiece)(nil),   // 27: kaboomproto.DeployPiece
	(*Location)(nil),      // 28: kaboomproto.Location
}
var file_move_proto_depIdxs = []int32{
	2,  // 0: kaboomproto.KaboomMove.pawn_move:type_name -> kaboomproto.PawnMove
	3,  // 1: kaboomproto.KaboomMove.pawn_capture:type_name -> kaboomproto.PawnCapture
	4,  // 2: kaboomproto.KaboomMove.pawn_bump:type_name -> kaboomproto.PawnBump
	5,  // 3: kaboomproto.KaboomMove.pawn_explosion:type_name -> kaboomproto.PawnExplosion
	6,  // 4: kaboomproto.KaboomMove.knight_move:type_name -> kaboomproto.KnightMove
	7,  // 5: kaboomproto.KaboomMove.knight_capture:type_name -> kaboomproto.KnightCapture
	8,  // 6: kaboomproto.KaboomMove.knight_bump:type_name -> kaboomproto.KnightBump
	9,  // 7: kaboomproto.KaboomMove.knight_stomp:type_name -> kaboomproto.KnightStomp
	10, // 8: kaboomproto.KaboomMove.bishop_move:type_name -> kaboomproto.BishopMove
	11, // 9: kaboomproto.KaboomMove.bishop_capture:type_name -> kaboomproto.BishopCapture
	12, // 10: kaboomproto.KaboomMove.bishop_bump:type_name -> kaboomproto.BishopBump
	13, // 11: kaboomproto.KaboomMove.bishop_snipe:type_name -> kaboomproto.BishopSnipe
	14, // 12: kaboomproto.KaboomMove.roomove:type_name -> kaboomproto.RookMove
	15, // 13: kaboomproto.KaboomMove.roocapture:type_name -> kaboomproto.RookCapture
	16, // 14: kaboomproto.KaboomMove.roobump:type_name -> kaboomproto.RookBump
	17, // 15: kaboomproto.KaboomMove.rootackle:type_name -> kaboomproto.RookTackle
	18, // 16: kaboomproto.KaboomMove.queen_move:type_name -> kaboomproto.QueenMove
	19, // 17: kaboomproto.KaboomMove.queen_capture:type_name -> kaboomproto.QueenCapture
	20, // 18: kaboomproto.KaboomMove.queen_bump:type_name -> kaboomproto.QueenBump
	21, // 19: kaboomproto.KaboomMove.queen_nova:type_name -> kaboomproto.QueenNova
	22, // 20: kaboomproto.KaboomMove.king_move:type_name -> kaboomproto.KingMove
	23, // 21: kaboomproto.KaboomMove.king_capture:type_name -> kaboomproto.KingCapture
	24, // 22: kaboomproto.KaboomMove.king_bump:type_name -> kaboomproto.KingBump
	1,  // 23: kaboomproto.KaboomMove.king_control:type_name -> kaboomproto.KingControl
	25, // 24: kaboomproto.KaboomMove.king_castle:type_name -> kaboomproto.KingCastle
	26, // 25: kaboomproto.KaboomMove.resign:type_name -> kaboomproto.Resign
	27, // 26: kaboomproto.KaboomMove.deploy_piece:type_name -> kaboomproto.DeployPiece
	28, // 27: kaboomproto.KingControl.king:type_name -> kaboomproto.Location
	0,  // 28: kaboomproto.KingControl.control_move:type_name -> kaboomproto.KaboomMove
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_move_proto_init() }
func file_move_proto_init() {
	if File_move_proto != nil {
		return
	}
	file_location_proto_init()
	file_move_classic_proto_init()
	file_move_kaboom_proto_init()
	file_move_proto_msgTypes[0].OneofWrappers = []any{
		(*KaboomMove_PawnMove)(nil),
		(*KaboomMove_PawnCapture)(nil),
		(*KaboomMove_PawnBump)(nil),
		(*KaboomMove_PawnExplosion)(nil),
		(*KaboomMove_KnightMove)(nil),
		(*KaboomMove_KnightCapture)(nil),
		(*KaboomMove_KnightBump)(nil),
		(*KaboomMove_KnightStomp)(nil),
		(*KaboomMove_BishopMove)(nil),
		(*KaboomMove_BishopCapture)(nil),
		(*KaboomMove_BishopBump)(nil),
		(*KaboomMove_BishopSnipe)(nil),
		(*KaboomMove_Roomove)(nil),
		(*KaboomMove_Roocapture)(nil),
		(*KaboomMove_Roobump)(nil),
		(*KaboomMove_Rootackle)(nil),
		(*KaboomMove_QueenMove)(nil),
		(*KaboomMove_QueenCapture)(nil),
		(*KaboomMove_QueenBump)(nil),
		(*KaboomMove_QueenNova)(nil),
		(*KaboomMove_KingMove)(nil),
		(*KaboomMove_KingCapture)(nil),
		(*KaboomMove_KingBump)(nil),
		(*KaboomMove_KingControl)(nil),
		(*KaboomMove_KingCastle)(nil),
		(*KaboomMove_Resign)(nil),
		(*KaboomMove_DeployPiece)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_move_proto_rawDesc), len(file_move_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_move_proto_goTypes,
		DependencyIndexes: file_move_proto_depIdxs,
		MessageInfos:      file_move_proto_msgTypes,
	}.Build()
	File_move_proto = out.File
	file_move_proto_goTypes = nil
	file_move_proto_depIdxs = nil
}
