// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: pawn.proto

package kaboomproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PawnMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromRow       int32                  `protobuf:"varint,1,opt,name=from_row,json=fromRow,proto3" json:"from_row,omitempty"`
	FromCol       int32                  `protobuf:"varint,2,opt,name=from_col,json=fromCol,proto3" json:"from_col,omitempty"`
	ToRow         int32                  `protobuf:"varint,3,opt,name=to_row,json=toRow,proto3" json:"to_row,omitempty"`
	ToCol         int32                  `protobuf:"varint,4,opt,name=to_col,json=toCol,proto3" json:"to_col,omitempty"`
	Promotion     PieceType              `protobuf:"varint,5,opt,name=promotion,proto3,enum=kaboomproto.PieceType" json:"promotion,omitempty"` // optional promotion piece type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PawnMove) Reset() {
	*x = PawnMove{}
	mi := &file_pawn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PawnMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PawnMove) ProtoMessage() {}

func (x *PawnMove) ProtoReflect() protoreflect.Message {
	mi := &file_pawn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PawnMove.ProtoReflect.Descriptor instead.
func (*PawnMove) Descriptor() ([]byte, []int) {
	return file_pawn_proto_rawDescGZIP(), []int{0}
}

func (x *PawnMove) GetFromRow() int32 {
	if x != nil {
		return x.FromRow
	}
	return 0
}

func (x *PawnMove) GetFromCol() int32 {
	if x != nil {
		return x.FromCol
	}
	return 0
}

func (x *PawnMove) GetToRow() int32 {
	if x != nil {
		return x.ToRow
	}
	return 0
}

func (x *PawnMove) GetToCol() int32 {
	if x != nil {
		return x.ToCol
	}
	return 0
}

func (x *PawnMove) GetPromotion() PieceType {
	if x != nil {
		return x.Promotion
	}
	return PieceType_PAWN
}

type PawnBump struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromRow       int32                  `protobuf:"varint,1,opt,name=from_row,json=fromRow,proto3" json:"from_row,omitempty"`
	FromCol       int32                  `protobuf:"varint,2,opt,name=from_col,json=fromCol,proto3" json:"from_col,omitempty"`
	ToRow         int32                  `protobuf:"varint,3,opt,name=to_row,json=toRow,proto3" json:"to_row,omitempty"`
	ToCol         int32                  `protobuf:"varint,4,opt,name=to_col,json=toCol,proto3" json:"to_col,omitempty"`
	Promotion     PieceType              `protobuf:"varint,5,opt,name=promotion,proto3,enum=kaboomproto.PieceType" json:"promotion,omitempty"` // optional promotion piece type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PawnBump) Reset() {
	*x = PawnBump{}
	mi := &file_pawn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PawnBump) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PawnBump) ProtoMessage() {}

func (x *PawnBump) ProtoReflect() protoreflect.Message {
	mi := &file_pawn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PawnBump.ProtoReflect.Descriptor instead.
func (*PawnBump) Descriptor() ([]byte, []int) {
	return file_pawn_proto_rawDescGZIP(), []int{1}
}

func (x *PawnBump) GetFromRow() int32 {
	if x != nil {
		return x.FromRow
	}
	return 0
}

func (x *PawnBump) GetFromCol() int32 {
	if x != nil {
		return x.FromCol
	}
	return 0
}

func (x *PawnBump) GetToRow() int32 {
	if x != nil {
		return x.ToRow
	}
	return 0
}

func (x *PawnBump) GetToCol() int32 {
	if x != nil {
		return x.ToCol
	}
	return 0
}

func (x *PawnBump) GetPromotion() PieceType {
	if x != nil {
		return x.Promotion
	}
	return PieceType_PAWN
}

type PawnKaboom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           int32                  `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Col           int32                  `protobuf:"varint,2,opt,name=col,proto3" json:"col,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PawnKaboom) Reset() {
	*x = PawnKaboom{}
	mi := &file_pawn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PawnKaboom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PawnKaboom) ProtoMessage() {}

func (x *PawnKaboom) ProtoReflect() protoreflect.Message {
	mi := &file_pawn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PawnKaboom.ProtoReflect.Descriptor instead.
func (*PawnKaboom) Descriptor() ([]byte, []int) {
	return file_pawn_proto_rawDescGZIP(), []int{2}
}

func (x *PawnKaboom) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *PawnKaboom) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

var File_pawn_proto protoreflect.FileDescriptor

const file_pawn_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"pawn.proto\x12\vkaboomproto\x1a\vpiece.proto\"\xa4\x01\n" +
	"\bPawnMove\x12\x19\n" +
	"\bfrom_row\x18\x01 \x01(\x05R\afromRow\x12\x19\n" +
	"\bfrom_col\x18\x02 \x01(\x05R\afromCol\x12\x15\n" +
	"\x06to_row\x18\x03 \x01(\x05R\x05toRow\x12\x15\n" +
	"\x06to_col\x18\x04 \x01(\x05R\x05toCol\x124\n" +
	"\tpromotion\x18\x05 \x01(\x0e2\x16.kaboomproto.PieceTypeR\tpromotion\"\xa4\x01\n" +
	"\bPawnBump\x12\x19\n" +
	"\bfrom_row\x18\x01 \x01(\x05R\afromRow\x12\x19\n" +
	"\bfrom_col\x18\x02 \x01(\x05R\afromCol\x12\x15\n" +
	"\x06to_row\x18\x03 \x01(\x05R\x05toRow\x12\x15\n" +
	"\x06to_col\x18\x04 \x01(\x05R\x05toCol\x124\n" +
	"\tpromotion\x18\x05 \x01(\x0e2\x16.kaboomproto.PieceTypeR\tpromotion\"0\n" +
	"\n" +
	"PawnKaboom\x12\x10\n" +
	"\x03row\x18\x01 \x01(\x05R\x03row\x12\x10\n" +
	"\x03col\x18\x02 \x01(\x05R\x03colB1Z/github.com/fsufitch/kaboom/proto/go;kaboomprotob\x06proto3"

var (
	file_pawn_proto_rawDescOnce sync.Once
	file_pawn_proto_rawDescData []byte
)

func file_pawn_proto_rawDescGZIP() []byte {
	file_pawn_proto_rawDescOnce.Do(func() {
		file_pawn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pawn_proto_rawDesc), len(file_pawn_proto_rawDesc)))
	})
	return file_pawn_proto_rawDescData
}

var file_pawn_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pawn_proto_goTypes = []any{
	(*PawnMove)(nil),   // 0: kaboomproto.PawnMove
	(*PawnBump)(nil),   // 1: kaboomproto.PawnBump
	(*PawnKaboom)(nil), // 2: kaboomproto.PawnKaboom
	(PieceType)(0),     // 3: kaboomproto.PieceType
}
var file_pawn_proto_depIdxs = []int32{
	3, // 0: kaboomproto.PawnMove.promotion:type_name -> kaboomproto.PieceType
	3, // 1: kaboomproto.PawnBump.promotion:type_name -> kaboomproto.PieceType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pawn_proto_init() }
func file_pawn_proto_init() {
	if File_pawn_proto != nil {
		return
	}
	file_piece_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pawn_proto_rawDesc), len(file_pawn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pawn_proto_goTypes,
		DependencyIndexes: file_pawn_proto_depIdxs,
		MessageInfos:      file_pawn_proto_msgTypes,
	}.Build()
	File_pawn_proto = out.File
	file_pawn_proto_goTypes = nil
	file_pawn_proto_depIdxs = nil
}
