// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: pawn_moves.proto

package kaboomproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PawnRegularMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *Position              `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            *Position              `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Promotion     PieceType              `protobuf:"varint,10,opt,name=promotion,proto3,enum=kaboomproto.PieceType" json:"promotion,omitempty"` // optional promotion piece type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PawnRegularMove) Reset() {
	*x = PawnRegularMove{}
	mi := &file_pawn_moves_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PawnRegularMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PawnRegularMove) ProtoMessage() {}

func (x *PawnRegularMove) ProtoReflect() protoreflect.Message {
	mi := &file_pawn_moves_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PawnRegularMove.ProtoReflect.Descriptor instead.
func (*PawnRegularMove) Descriptor() ([]byte, []int) {
	return file_pawn_moves_proto_rawDescGZIP(), []int{0}
}

func (x *PawnRegularMove) GetFrom() *Position {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *PawnRegularMove) GetTo() *Position {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *PawnRegularMove) GetPromotion() PieceType {
	if x != nil {
		return x.Promotion
	}
	return PieceType_INVALID_PIECE
}

type PawnBump struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *Position              `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            *Position              `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Promotion     PieceType              `protobuf:"varint,10,opt,name=promotion,proto3,enum=kaboomproto.PieceType" json:"promotion,omitempty"` // optional promotion piece type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PawnBump) Reset() {
	*x = PawnBump{}
	mi := &file_pawn_moves_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PawnBump) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PawnBump) ProtoMessage() {}

func (x *PawnBump) ProtoReflect() protoreflect.Message {
	mi := &file_pawn_moves_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PawnBump.ProtoReflect.Descriptor instead.
func (*PawnBump) Descriptor() ([]byte, []int) {
	return file_pawn_moves_proto_rawDescGZIP(), []int{1}
}

func (x *PawnBump) GetFrom() *Position {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *PawnBump) GetTo() *Position {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *PawnBump) GetPromotion() PieceType {
	if x != nil {
		return x.Promotion
	}
	return PieceType_INVALID_PIECE
}

type PawnKaboom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Position              `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PawnKaboom) Reset() {
	*x = PawnKaboom{}
	mi := &file_pawn_moves_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PawnKaboom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PawnKaboom) ProtoMessage() {}

func (x *PawnKaboom) ProtoReflect() protoreflect.Message {
	mi := &file_pawn_moves_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PawnKaboom.ProtoReflect.Descriptor instead.
func (*PawnKaboom) Descriptor() ([]byte, []int) {
	return file_pawn_moves_proto_rawDescGZIP(), []int{2}
}

func (x *PawnKaboom) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

var File_pawn_moves_proto protoreflect.FileDescriptor

const file_pawn_moves_proto_rawDesc = "" +
	"\n" +
	"\x10pawn_moves.proto\x12\vkaboomproto\x1a\vpiece.proto\x1a\x0eposition.proto\"\x99\x01\n" +
	"\x0fPawnRegularMove\x12)\n" +
	"\x04from\x18\x01 \x01(\v2\x15.kaboomproto.PositionR\x04from\x12%\n" +
	"\x02to\x18\x02 \x01(\v2\x15.kaboomproto.PositionR\x02to\x124\n" +
	"\tpromotion\x18\n" +
	" \x01(\x0e2\x16.kaboomproto.PieceTypeR\tpromotion\"\x92\x01\n" +
	"\bPawnBump\x12)\n" +
	"\x04from\x18\x01 \x01(\v2\x15.kaboomproto.PositionR\x04from\x12%\n" +
	"\x02to\x18\x02 \x01(\v2\x15.kaboomproto.PositionR\x02to\x124\n" +
	"\tpromotion\x18\n" +
	" \x01(\x0e2\x16.kaboomproto.PieceTypeR\tpromotion\"?\n" +
	"\n" +
	"PawnKaboom\x121\n" +
	"\bposition\x18\x01 \x01(\v2\x15.kaboomproto.PositionR\bpositionB1Z/github.com/fsufitch/kaboom/proto/go;kaboomprotob\x06proto3"

var (
	file_pawn_moves_proto_rawDescOnce sync.Once
	file_pawn_moves_proto_rawDescData []byte
)

func file_pawn_moves_proto_rawDescGZIP() []byte {
	file_pawn_moves_proto_rawDescOnce.Do(func() {
		file_pawn_moves_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pawn_moves_proto_rawDesc), len(file_pawn_moves_proto_rawDesc)))
	})
	return file_pawn_moves_proto_rawDescData
}

var file_pawn_moves_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pawn_moves_proto_goTypes = []any{
	(*PawnRegularMove)(nil), // 0: kaboomproto.PawnRegularMove
	(*PawnBump)(nil),        // 1: kaboomproto.PawnBump
	(*PawnKaboom)(nil),      // 2: kaboomproto.PawnKaboom
	(*Position)(nil),        // 3: kaboomproto.Position
	(PieceType)(0),          // 4: kaboomproto.PieceType
}
var file_pawn_moves_proto_depIdxs = []int32{
	3, // 0: kaboomproto.PawnRegularMove.from:type_name -> kaboomproto.Position
	3, // 1: kaboomproto.PawnRegularMove.to:type_name -> kaboomproto.Position
	4, // 2: kaboomproto.PawnRegularMove.promotion:type_name -> kaboomproto.PieceType
	3, // 3: kaboomproto.PawnBump.from:type_name -> kaboomproto.Position
	3, // 4: kaboomproto.PawnBump.to:type_name -> kaboomproto.Position
	4, // 5: kaboomproto.PawnBump.promotion:type_name -> kaboomproto.PieceType
	3, // 6: kaboomproto.PawnKaboom.position:type_name -> kaboomproto.Position
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_pawn_moves_proto_init() }
func file_pawn_moves_proto_init() {
	if File_pawn_moves_proto != nil {
		return
	}
	file_piece_proto_init()
	file_position_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pawn_moves_proto_rawDesc), len(file_pawn_moves_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pawn_moves_proto_goTypes,
		DependencyIndexes: file_pawn_moves_proto_depIdxs,
		MessageInfos:      file_pawn_moves_proto_msgTypes,
	}.Build()
	File_pawn_moves_proto = out.File
	file_pawn_moves_proto_goTypes = nil
	file_pawn_moves_proto_depIdxs = nil
}
