// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: piece.proto

package kaboomproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PieceKind represents the different kinds of chess pieces.
type PieceKind int32

const (
	PieceKind_INVALID_PIECE PieceKind = 0
	PieceKind_PAWN          PieceKind = 1
	PieceKind_KNIGHT        PieceKind = 2
	PieceKind_BISHOP        PieceKind = 3
	PieceKind_ROOK          PieceKind = 4
	PieceKind_QUEEN         PieceKind = 5
	PieceKind_KING          PieceKind = 6
)

// Enum value maps for PieceKind.
var (
	PieceKind_name = map[int32]string{
		0: "INVALID_PIECE",
		1: "PAWN",
		2: "KNIGHT",
		3: "BISHOP",
		4: "ROOK",
		5: "QUEEN",
		6: "KING",
	}
	PieceKind_value = map[string]int32{
		"INVALID_PIECE": 0,
		"PAWN":          1,
		"KNIGHT":        2,
		"BISHOP":        3,
		"ROOK":          4,
		"QUEEN":         5,
		"KING":          6,
	}
)

func (x PieceKind) Enum() *PieceKind {
	p := new(PieceKind)
	*p = x
	return p
}

func (x PieceKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PieceKind) Descriptor() protoreflect.EnumDescriptor {
	return file_piece_proto_enumTypes[0].Descriptor()
}

func (PieceKind) Type() protoreflect.EnumType {
	return &file_piece_proto_enumTypes[0]
}

func (x PieceKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PieceKind.Descriptor instead.
func (PieceKind) EnumDescriptor() ([]byte, []int) {
	return file_piece_proto_rawDescGZIP(), []int{0}
}

// ChessPiece represents a specific chess piece in the game.
// It is "location-aware" and knows which board it is on, its position, and its zone.
type ChessPiece struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Kind          PieceKind              `protobuf:"varint,2,opt,name=kind,proto3,enum=kaboomproto.PieceKind" json:"kind,omitempty"`
	Color         Color                  `protobuf:"varint,3,opt,name=color,proto3,enum=kaboomproto.Color" json:"color,omitempty"`
	BoardUuid     string                 `protobuf:"bytes,4,opt,name=board_uuid,json=boardUuid,proto3" json:"board_uuid,omitempty"`
	Position      *Position              `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	Zone          ZoneKind               `protobuf:"varint,6,opt,name=zone,proto3,enum=kaboomproto.ZoneKind" json:"zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChessPiece) Reset() {
	*x = ChessPiece{}
	mi := &file_piece_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChessPiece) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChessPiece) ProtoMessage() {}

func (x *ChessPiece) ProtoReflect() protoreflect.Message {
	mi := &file_piece_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChessPiece.ProtoReflect.Descriptor instead.
func (*ChessPiece) Descriptor() ([]byte, []int) {
	return file_piece_proto_rawDescGZIP(), []int{0}
}

func (x *ChessPiece) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ChessPiece) GetKind() PieceKind {
	if x != nil {
		return x.Kind
	}
	return PieceKind_INVALID_PIECE
}

func (x *ChessPiece) GetColor() Color {
	if x != nil {
		return x.Color
	}
	return Color_COLOR_INVALID
}

func (x *ChessPiece) GetBoardUuid() string {
	if x != nil {
		return x.BoardUuid
	}
	return ""
}

func (x *ChessPiece) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *ChessPiece) GetZone() ZoneKind {
	if x != nil {
		return x.Zone
	}
	return ZoneKind_ZONE_INVALID
}

var File_piece_proto protoreflect.FileDescriptor

const file_piece_proto_rawDesc = "" +
	"\n" +
	"\vpiece.proto\x12\vkaboomproto\x1a\vcolor.proto\x1a\x0eposition.proto\"\xf3\x01\n" +
	"\n" +
	"ChessPiece\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12*\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x16.kaboomproto.PieceKindR\x04kind\x12(\n" +
	"\x05color\x18\x03 \x01(\x0e2\x12.kaboomproto.ColorR\x05color\x12\x1d\n" +
	"\n" +
	"board_uuid\x18\x04 \x01(\tR\tboardUuid\x121\n" +
	"\bposition\x18\x05 \x01(\v2\x15.kaboomproto.PositionR\bposition\x12)\n" +
	"\x04zone\x18\x06 \x01(\x0e2\x15.kaboomproto.ZoneKindR\x04zone*_\n" +
	"\tPieceKind\x12\x11\n" +
	"\rINVALID_PIECE\x10\x00\x12\b\n" +
	"\x04PAWN\x10\x01\x12\n" +
	"\n" +
	"\x06KNIGHT\x10\x02\x12\n" +
	"\n" +
	"\x06BISHOP\x10\x03\x12\b\n" +
	"\x04ROOK\x10\x04\x12\t\n" +
	"\x05QUEEN\x10\x05\x12\b\n" +
	"\x04KING\x10\x06B1Z/github.com/fsufitch/kaboom/proto/go;kaboomprotob\x06proto3"

var (
	file_piece_proto_rawDescOnce sync.Once
	file_piece_proto_rawDescData []byte
)

func file_piece_proto_rawDescGZIP() []byte {
	file_piece_proto_rawDescOnce.Do(func() {
		file_piece_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_piece_proto_rawDesc), len(file_piece_proto_rawDesc)))
	})
	return file_piece_proto_rawDescData
}

var file_piece_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_piece_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_piece_proto_goTypes = []any{
	(PieceKind)(0),     // 0: kaboomproto.PieceKind
	(*ChessPiece)(nil), // 1: kaboomproto.ChessPiece
	(Color)(0),         // 2: kaboomproto.Color
	(*Position)(nil),   // 3: kaboomproto.Position
	(ZoneKind)(0),      // 4: kaboomproto.ZoneKind
}
var file_piece_proto_depIdxs = []int32{
	0, // 0: kaboomproto.ChessPiece.kind:type_name -> kaboomproto.PieceKind
	2, // 1: kaboomproto.ChessPiece.color:type_name -> kaboomproto.Color
	3, // 2: kaboomproto.ChessPiece.position:type_name -> kaboomproto.Position
	4, // 3: kaboomproto.ChessPiece.zone:type_name -> kaboomproto.ZoneKind
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_piece_proto_init() }
func file_piece_proto_init() {
	if File_piece_proto != nil {
		return
	}
	file_color_proto_init()
	file_position_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_piece_proto_rawDesc), len(file_piece_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_piece_proto_goTypes,
		DependencyIndexes: file_piece_proto_depIdxs,
		EnumInfos:         file_piece_proto_enumTypes,
		MessageInfos:      file_piece_proto_msgTypes,
	}.Build()
	File_piece_proto = out.File
	file_piece_proto_goTypes = nil
	file_piece_proto_depIdxs = nil
}
