// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: piece.proto

package kaboomproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PieceType int32

const (
	PieceType_INVALID_PIECE PieceType = 0
	PieceType_PAWN          PieceType = 1
	PieceType_KNIGHT        PieceType = 2
	PieceType_BISHOP        PieceType = 3
	PieceType_ROOK          PieceType = 4
	PieceType_QUEEN         PieceType = 5
	PieceType_KING          PieceType = 6
)

// Enum value maps for PieceType.
var (
	PieceType_name = map[int32]string{
		0: "INVALID_PIECE",
		1: "PAWN",
		2: "KNIGHT",
		3: "BISHOP",
		4: "ROOK",
		5: "QUEEN",
		6: "KING",
	}
	PieceType_value = map[string]int32{
		"INVALID_PIECE": 0,
		"PAWN":          1,
		"KNIGHT":        2,
		"BISHOP":        3,
		"ROOK":          4,
		"QUEEN":         5,
		"KING":          6,
	}
)

func (x PieceType) Enum() *PieceType {
	p := new(PieceType)
	*p = x
	return p
}

func (x PieceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PieceType) Descriptor() protoreflect.EnumDescriptor {
	return file_piece_proto_enumTypes[0].Descriptor()
}

func (PieceType) Type() protoreflect.EnumType {
	return &file_piece_proto_enumTypes[0]
}

func (x PieceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PieceType.Descriptor instead.
func (PieceType) EnumDescriptor() ([]byte, []int) {
	return file_piece_proto_rawDescGZIP(), []int{0}
}

type Color int32

const (
	Color_INVALID_COLOR Color = 0
	Color_WHITE         Color = 1
	Color_BLACK         Color = 2
)

// Enum value maps for Color.
var (
	Color_name = map[int32]string{
		0: "INVALID_COLOR",
		1: "WHITE",
		2: "BLACK",
	}
	Color_value = map[string]int32{
		"INVALID_COLOR": 0,
		"WHITE":         1,
		"BLACK":         2,
	}
)

func (x Color) Enum() *Color {
	p := new(Color)
	*p = x
	return p
}

func (x Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color) Descriptor() protoreflect.EnumDescriptor {
	return file_piece_proto_enumTypes[1].Descriptor()
}

func (Color) Type() protoreflect.EnumType {
	return &file_piece_proto_enumTypes[1]
}

func (x Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Color.Descriptor instead.
func (Color) EnumDescriptor() ([]byte, []int) {
	return file_piece_proto_rawDescGZIP(), []int{1}
}

type ChessPiece struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PieceType              `protobuf:"varint,1,opt,name=type,proto3,enum=kaboomproto.PieceType" json:"type,omitempty"`
	Color         Color                  `protobuf:"varint,2,opt,name=color,proto3,enum=kaboomproto.Color" json:"color,omitempty"`
	Position      *Position              `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChessPiece) Reset() {
	*x = ChessPiece{}
	mi := &file_piece_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChessPiece) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChessPiece) ProtoMessage() {}

func (x *ChessPiece) ProtoReflect() protoreflect.Message {
	mi := &file_piece_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChessPiece.ProtoReflect.Descriptor instead.
func (*ChessPiece) Descriptor() ([]byte, []int) {
	return file_piece_proto_rawDescGZIP(), []int{0}
}

func (x *ChessPiece) GetType() PieceType {
	if x != nil {
		return x.Type
	}
	return PieceType_INVALID_PIECE
}

func (x *ChessPiece) GetColor() Color {
	if x != nil {
		return x.Color
	}
	return Color_INVALID_COLOR
}

func (x *ChessPiece) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

var File_piece_proto protoreflect.FileDescriptor

const file_piece_proto_rawDesc = "" +
	"\n" +
	"\vpiece.proto\x12\vkaboomproto\x1a\x0eposition.proto\"\x95\x01\n" +
	"\n" +
	"ChessPiece\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.kaboomproto.PieceTypeR\x04type\x12(\n" +
	"\x05color\x18\x02 \x01(\x0e2\x12.kaboomproto.ColorR\x05color\x121\n" +
	"\bposition\x18\x03 \x01(\v2\x15.kaboomproto.PositionR\bposition*_\n" +
	"\tPieceType\x12\x11\n" +
	"\rINVALID_PIECE\x10\x00\x12\b\n" +
	"\x04PAWN\x10\x01\x12\n" +
	"\n" +
	"\x06KNIGHT\x10\x02\x12\n" +
	"\n" +
	"\x06BISHOP\x10\x03\x12\b\n" +
	"\x04ROOK\x10\x04\x12\t\n" +
	"\x05QUEEN\x10\x05\x12\b\n" +
	"\x04KING\x10\x06*0\n" +
	"\x05Color\x12\x11\n" +
	"\rINVALID_COLOR\x10\x00\x12\t\n" +
	"\x05WHITE\x10\x01\x12\t\n" +
	"\x05BLACK\x10\x02B1Z/github.com/fsufitch/kaboom/proto/go;kaboomprotob\x06proto3"

var (
	file_piece_proto_rawDescOnce sync.Once
	file_piece_proto_rawDescData []byte
)

func file_piece_proto_rawDescGZIP() []byte {
	file_piece_proto_rawDescOnce.Do(func() {
		file_piece_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_piece_proto_rawDesc), len(file_piece_proto_rawDesc)))
	})
	return file_piece_proto_rawDescData
}

var file_piece_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_piece_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_piece_proto_goTypes = []any{
	(PieceType)(0),     // 0: kaboomproto.PieceType
	(Color)(0),         // 1: kaboomproto.Color
	(*ChessPiece)(nil), // 2: kaboomproto.ChessPiece
	(*Position)(nil),   // 3: kaboomproto.Position
}
var file_piece_proto_depIdxs = []int32{
	0, // 0: kaboomproto.ChessPiece.type:type_name -> kaboomproto.PieceType
	1, // 1: kaboomproto.ChessPiece.color:type_name -> kaboomproto.Color
	3, // 2: kaboomproto.ChessPiece.position:type_name -> kaboomproto.Position
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_piece_proto_init() }
func file_piece_proto_init() {
	if File_piece_proto != nil {
		return
	}
	file_position_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_piece_proto_rawDesc), len(file_piece_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_piece_proto_goTypes,
		DependencyIndexes: file_piece_proto_depIdxs,
		EnumInfos:         file_piece_proto_enumTypes,
		MessageInfos:      file_piece_proto_msgTypes,
	}.Build()
	File_piece_proto = out.File
	file_piece_proto_goTypes = nil
	file_piece_proto_depIdxs = nil
}
