// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: position.proto

package kaboomproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ZoneKind represents different zones a piece can be in.
type ZoneKind int32

const (
	ZoneKind_ZONE_INVALID   ZoneKind = 0
	ZoneKind_ZONE_BOARD     ZoneKind = 1 // On the main chess board
	ZoneKind_ZONE_GRAVEYARD ZoneKind = 2 // Captured
	ZoneKind_ZONE_BENCH     ZoneKind = 3 // Ready to be deployed
	ZoneKind_ZONE_TEMPORARY ZoneKind = 4 // For transient states
)

// Enum value maps for ZoneKind.
var (
	ZoneKind_name = map[int32]string{
		0: "ZONE_INVALID",
		1: "ZONE_BOARD",
		2: "ZONE_GRAVEYARD",
		3: "ZONE_BENCH",
		4: "ZONE_TEMPORARY",
	}
	ZoneKind_value = map[string]int32{
		"ZONE_INVALID":   0,
		"ZONE_BOARD":     1,
		"ZONE_GRAVEYARD": 2,
		"ZONE_BENCH":     3,
		"ZONE_TEMPORARY": 4,
	}
)

func (x ZoneKind) Enum() *ZoneKind {
	p := new(ZoneKind)
	*p = x
	return p
}

func (x ZoneKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ZoneKind) Descriptor() protoreflect.EnumDescriptor {
	return file_position_proto_enumTypes[0].Descriptor()
}

func (ZoneKind) Type() protoreflect.EnumType {
	return &file_position_proto_enumTypes[0]
}

func (x ZoneKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ZoneKind.Descriptor instead.
func (ZoneKind) EnumDescriptor() ([]byte, []int) {
	return file_position_proto_rawDescGZIP(), []int{0}
}

// Position represents a location on the chess board.
// Rows/cols are zero-indexed using algebraic coordinates:
//   A1 = (row=0,col=0), A8 = (row=7,col=0), H1 = (row=0,col=7), H8 = (row=7,col=7).
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           int32                  `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Col           int32                  `protobuf:"varint,2,opt,name=col,proto3" json:"col,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_position_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_position_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_position_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *Position) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

// Vector represents a directional offset on the chess board.
type Vector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DRow          int32                  `protobuf:"varint,1,opt,name=d_row,json=dRow,proto3" json:"d_row,omitempty"`
	DCol          int32                  `protobuf:"varint,2,opt,name=d_col,json=dCol,proto3" json:"d_col,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_position_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_position_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_position_proto_rawDescGZIP(), []int{1}
}

func (x *Vector) GetDRow() int32 {
	if x != nil {
		return x.DRow
	}
	return 0
}

func (x *Vector) GetDCol() int32 {
	if x != nil {
		return x.DCol
	}
	return 0
}

var File_position_proto protoreflect.FileDescriptor

const file_position_proto_rawDesc = "" +
	"\n" +
	"\x0eposition.proto\x12\vkaboomproto\".\n" +
	"\bPosition\x12\x10\n" +
	"\x03row\x18\x01 \x01(\x05R\x03row\x12\x10\n" +
	"\x03col\x18\x02 \x01(\x05R\x03col\"2\n" +
	"\x06Vector\x12\x13\n" +
	"\x05d_row\x18\x01 \x01(\x05R\x04dRow\x12\x13\n" +
	"\x05d_col\x18\x02 \x01(\x05R\x04dCol*d\n" +
	"\bZoneKind\x12\x10\n" +
	"\fZONE_INVALID\x10\x00\x12\x0e\n" +
	"\n" +
	"ZONE_BOARD\x10\x01\x12\x12\n" +
	"\x0eZONE_GRAVEYARD\x10\x02\x12\x0e\n" +
	"\n" +
	"ZONE_BENCH\x10\x03\x12\x12\n" +
	"\x0eZONE_TEMPORARY\x10\x04B1Z/github.com/fsufitch/kaboom/proto/go;kaboomprotob\x06proto3"

var (
	file_position_proto_rawDescOnce sync.Once
	file_position_proto_rawDescData []byte
)

func file_position_proto_rawDescGZIP() []byte {
	file_position_proto_rawDescOnce.Do(func() {
		file_position_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_position_proto_rawDesc), len(file_position_proto_rawDesc)))
	})
	return file_position_proto_rawDescData
}

var file_position_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_position_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_position_proto_goTypes = []any{
	(ZoneKind)(0),    // 0: kaboomproto.ZoneKind
	(*Position)(nil), // 1: kaboomproto.Position
	(*Vector)(nil),   // 2: kaboomproto.Vector
}
var file_position_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_position_proto_init() }
func file_position_proto_init() {
	if File_position_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_position_proto_rawDesc), len(file_position_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_position_proto_goTypes,
		DependencyIndexes: file_position_proto_depIdxs,
		EnumInfos:         file_position_proto_enumTypes,
		MessageInfos:      file_position_proto_msgTypes,
	}.Build()
	File_position_proto = out.File
	file_position_proto_goTypes = nil
	file_position_proto_depIdxs = nil
}
