// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: turn.proto

package kaboomproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Turn represents a single turn taken by a player in the game. It is a container for "a player did something".
// Note: this may include multiple moves, affecting multiple boards.
type Turn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	PlayerUuid    string                 `protobuf:"bytes,2,opt,name=player_uuid,json=playerUuid,proto3" json:"player_uuid,omitempty"`
	Moves         []*KaboomMove          `protobuf:"bytes,10,rep,name=moves,proto3" json:"moves,omitempty"`
	Deltas        []*Delta               `protobuf:"bytes,20,rep,name=deltas,proto3" json:"deltas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Turn) Reset() {
	*x = Turn{}
	mi := &file_turn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Turn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Turn) ProtoMessage() {}

func (x *Turn) ProtoReflect() protoreflect.Message {
	mi := &file_turn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Turn.ProtoReflect.Descriptor instead.
func (*Turn) Descriptor() ([]byte, []int) {
	return file_turn_proto_rawDescGZIP(), []int{0}
}

func (x *Turn) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Turn) GetPlayerUuid() string {
	if x != nil {
		return x.PlayerUuid
	}
	return ""
}

func (x *Turn) GetMoves() []*KaboomMove {
	if x != nil {
		return x.Moves
	}
	return nil
}

func (x *Turn) GetDeltas() []*Delta {
	if x != nil {
		return x.Deltas
	}
	return nil
}

var File_turn_proto protoreflect.FileDescriptor

const file_turn_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"turn.proto\x12\vkaboomproto\x1a\n" +
	"move.proto\x1a\vdelta.proto\"\x96\x01\n" +
	"\x04Turn\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1f\n" +
	"\vplayer_uuid\x18\x02 \x01(\tR\n" +
	"playerUuid\x12-\n" +
	"\x05moves\x18\n" +
	" \x03(\v2\x17.kaboomproto.KaboomMoveR\x05moves\x12*\n" +
	"\x06deltas\x18\x14 \x03(\v2\x12.kaboomproto.DeltaR\x06deltasB1Z/github.com/fsufitch/kaboom/proto/go;kaboomprotob\x06proto3"

var (
	file_turn_proto_rawDescOnce sync.Once
	file_turn_proto_rawDescData []byte
)

func file_turn_proto_rawDescGZIP() []byte {
	file_turn_proto_rawDescOnce.Do(func() {
		file_turn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_turn_proto_rawDesc), len(file_turn_proto_rawDesc)))
	})
	return file_turn_proto_rawDescData
}

var file_turn_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_turn_proto_goTypes = []any{
	(*Turn)(nil),       // 0: kaboomproto.Turn
	(*KaboomMove)(nil), // 1: kaboomproto.KaboomMove
	(*Delta)(nil),      // 2: kaboomproto.Delta
}
var file_turn_proto_depIdxs = []int32{
	1, // 0: kaboomproto.Turn.moves:type_name -> kaboomproto.KaboomMove
	2, // 1: kaboomproto.Turn.deltas:type_name -> kaboomproto.Delta
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_turn_proto_init() }
func file_turn_proto_init() {
	if File_turn_proto != nil {
		return
	}
	file_move_proto_init()
	file_delta_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turn_proto_rawDesc), len(file_turn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_turn_proto_goTypes,
		DependencyIndexes: file_turn_proto_depIdxs,
		MessageInfos:      file_turn_proto_msgTypes,
	}.Build()
	File_turn_proto = out.File
	file_turn_proto_goTypes = nil
	file_turn_proto_depIdxs = nil
}
