// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: visual_hint.proto

package kaboomproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VisualHint provides information for the frontend to create visual effects corresponding to game events.
type VisualHint struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Uuid      string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	BoardUuid string                 `protobuf:"bytes,2,opt,name=board_uuid,json=boardUuid,proto3" json:"board_uuid,omitempty"`
	// Timing indicates when this visual hint should be displayed relative to other visual hints in the same TurnEffect.
	Timing int32 `protobuf:"varint,3,opt,name=timing,proto3" json:"timing,omitempty"`
	// Types that are valid to be assigned to Hint:
	//
	//	*VisualHint_Collision
	//	*VisualHint_Explosion
	//	*VisualHint_Stomp
	//	*VisualHint_Snipe
	//	*VisualHint_Nova
	//	*VisualHint_MindControl
	//	*VisualHint_Disintegration
	//	*VisualHint_Yeet
	Hint          isVisualHint_Hint `protobuf_oneof:"hint"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisualHint) Reset() {
	*x = VisualHint{}
	mi := &file_visual_hint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisualHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisualHint) ProtoMessage() {}

func (x *VisualHint) ProtoReflect() protoreflect.Message {
	mi := &file_visual_hint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisualHint.ProtoReflect.Descriptor instead.
func (*VisualHint) Descriptor() ([]byte, []int) {
	return file_visual_hint_proto_rawDescGZIP(), []int{0}
}

func (x *VisualHint) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *VisualHint) GetBoardUuid() string {
	if x != nil {
		return x.BoardUuid
	}
	return ""
}

func (x *VisualHint) GetTiming() int32 {
	if x != nil {
		return x.Timing
	}
	return 0
}

func (x *VisualHint) GetHint() isVisualHint_Hint {
	if x != nil {
		return x.Hint
	}
	return nil
}

func (x *VisualHint) GetCollision() *VisualHint__Collision {
	if x != nil {
		if x, ok := x.Hint.(*VisualHint_Collision); ok {
			return x.Collision
		}
	}
	return nil
}

func (x *VisualHint) GetExplosion() *VisualHint__Explosion {
	if x != nil {
		if x, ok := x.Hint.(*VisualHint_Explosion); ok {
			return x.Explosion
		}
	}
	return nil
}

func (x *VisualHint) GetStomp() *VisualHint__Stomp {
	if x != nil {
		if x, ok := x.Hint.(*VisualHint_Stomp); ok {
			return x.Stomp
		}
	}
	return nil
}

func (x *VisualHint) GetSnipe() *VisualHint__Snipe {
	if x != nil {
		if x, ok := x.Hint.(*VisualHint_Snipe); ok {
			return x.Snipe
		}
	}
	return nil
}

func (x *VisualHint) GetNova() *VisualHint__Nova {
	if x != nil {
		if x, ok := x.Hint.(*VisualHint_Nova); ok {
			return x.Nova
		}
	}
	return nil
}

func (x *VisualHint) GetMindControl() *VisualHint__MindControl {
	if x != nil {
		if x, ok := x.Hint.(*VisualHint_MindControl); ok {
			return x.MindControl
		}
	}
	return nil
}

func (x *VisualHint) GetDisintegration() *VisualHint__Disintegration {
	if x != nil {
		if x, ok := x.Hint.(*VisualHint_Disintegration); ok {
			return x.Disintegration
		}
	}
	return nil
}

func (x *VisualHint) GetYeet() *VisualHint__Yeet {
	if x != nil {
		if x, ok := x.Hint.(*VisualHint_Yeet); ok {
			return x.Yeet
		}
	}
	return nil
}

type isVisualHint_Hint interface {
	isVisualHint_Hint()
}

type VisualHint_Collision struct {
	Collision *VisualHint__Collision `protobuf:"bytes,10,opt,name=collision,proto3,oneof"`
}

type VisualHint_Explosion struct {
	Explosion *VisualHint__Explosion `protobuf:"bytes,11,opt,name=explosion,proto3,oneof"`
}

type VisualHint_Stomp struct {
	Stomp *VisualHint__Stomp `protobuf:"bytes,12,opt,name=stomp,proto3,oneof"`
}

type VisualHint_Snipe struct {
	Snipe *VisualHint__Snipe `protobuf:"bytes,13,opt,name=snipe,proto3,oneof"`
}

type VisualHint_Nova struct {
	Nova *VisualHint__Nova `protobuf:"bytes,14,opt,name=nova,proto3,oneof"`
}

type VisualHint_MindControl struct {
	MindControl *VisualHint__MindControl `protobuf:"bytes,15,opt,name=mind_control,json=mindControl,proto3,oneof"`
}

type VisualHint_Disintegration struct {
	Disintegration *VisualHint__Disintegration `protobuf:"bytes,16,opt,name=disintegration,proto3,oneof"`
}

type VisualHint_Yeet struct {
	Yeet *VisualHint__Yeet `protobuf:"bytes,17,opt,name=yeet,proto3,oneof"`
}

func (*VisualHint_Collision) isVisualHint_Hint() {}

func (*VisualHint_Explosion) isVisualHint_Hint() {}

func (*VisualHint_Stomp) isVisualHint_Hint() {}

func (*VisualHint_Snipe) isVisualHint_Hint() {}

func (*VisualHint_Nova) isVisualHint_Hint() {}

func (*VisualHint_MindControl) isVisualHint_Hint() {}

func (*VisualHint_Disintegration) isVisualHint_Hint() {}

func (*VisualHint_Yeet) isVisualHint_Hint() {}

// VisualHint__Collision indicates a visual effect for two pieces colliding (e.g., during a bump).
type VisualHint__Collision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PieceAUuid    string                 `protobuf:"bytes,2,opt,name=piece_a_uuid,json=pieceAUuid,proto3" json:"piece_a_uuid,omitempty"`
	PieceBUuid    string                 `protobuf:"bytes,3,opt,name=piece_b_uuid,json=pieceBUuid,proto3" json:"piece_b_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisualHint__Collision) Reset() {
	*x = VisualHint__Collision{}
	mi := &file_visual_hint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisualHint__Collision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisualHint__Collision) ProtoMessage() {}

func (x *VisualHint__Collision) ProtoReflect() protoreflect.Message {
	mi := &file_visual_hint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisualHint__Collision.ProtoReflect.Descriptor instead.
func (*VisualHint__Collision) Descriptor() ([]byte, []int) {
	return file_visual_hint_proto_rawDescGZIP(), []int{1}
}

func (x *VisualHint__Collision) GetPieceAUuid() string {
	if x != nil {
		return x.PieceAUuid
	}
	return ""
}

func (x *VisualHint__Collision) GetPieceBUuid() string {
	if x != nil {
		return x.PieceBUuid
	}
	return ""
}

// VisualHint__Explosion indicates a visual effect for an explosion at a specific position (e.g. a pawn exploding).
type VisualHint__Explosion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Position              `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisualHint__Explosion) Reset() {
	*x = VisualHint__Explosion{}
	mi := &file_visual_hint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisualHint__Explosion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisualHint__Explosion) ProtoMessage() {}

func (x *VisualHint__Explosion) ProtoReflect() protoreflect.Message {
	mi := &file_visual_hint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisualHint__Explosion.ProtoReflect.Descriptor instead.
func (*VisualHint__Explosion) Descriptor() ([]byte, []int) {
	return file_visual_hint_proto_rawDescGZIP(), []int{2}
}

func (x *VisualHint__Explosion) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

// VisualHint__Stomp indicates a visual effect for a piece stomping on a position (e.g. knight stomp)
type VisualHint__Stomp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Position              `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisualHint__Stomp) Reset() {
	*x = VisualHint__Stomp{}
	mi := &file_visual_hint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisualHint__Stomp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisualHint__Stomp) ProtoMessage() {}

func (x *VisualHint__Stomp) ProtoReflect() protoreflect.Message {
	mi := &file_visual_hint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisualHint__Stomp.ProtoReflect.Descriptor instead.
func (*VisualHint__Stomp) Descriptor() ([]byte, []int) {
	return file_visual_hint_proto_rawDescGZIP(), []int{3}
}

func (x *VisualHint__Stomp) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

// VisualHint__Snipe indicates a visual effect for a piece sniping another piece from a distance (e.g. bishop snipe).
type VisualHint__Snipe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *Position              `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            *Position              `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisualHint__Snipe) Reset() {
	*x = VisualHint__Snipe{}
	mi := &file_visual_hint_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisualHint__Snipe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisualHint__Snipe) ProtoMessage() {}

func (x *VisualHint__Snipe) ProtoReflect() protoreflect.Message {
	mi := &file_visual_hint_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisualHint__Snipe.ProtoReflect.Descriptor instead.
func (*VisualHint__Snipe) Descriptor() ([]byte, []int) {
	return file_visual_hint_proto_rawDescGZIP(), []int{4}
}

func (x *VisualHint__Snipe) GetFrom() *Position {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *VisualHint__Snipe) GetTo() *Position {
	if x != nil {
		return x.To
	}
	return nil
}

// VisualHint__Nova indicates a visual effect for a nova explosion at a specific position (e.g. queen nova).
type VisualHint__Nova struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Position              `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisualHint__Nova) Reset() {
	*x = VisualHint__Nova{}
	mi := &file_visual_hint_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisualHint__Nova) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisualHint__Nova) ProtoMessage() {}

func (x *VisualHint__Nova) ProtoReflect() protoreflect.Message {
	mi := &file_visual_hint_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisualHint__Nova.ProtoReflect.Descriptor instead.
func (*VisualHint__Nova) Descriptor() ([]byte, []int) {
	return file_visual_hint_proto_rawDescGZIP(), []int{5}
}

func (x *VisualHint__Nova) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

// VisualHint__MindControl indicates a visual effect for mind control between two pieces (e.g. king control).
type VisualHint__MindControl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PieceAUuid    string                 `protobuf:"bytes,2,opt,name=piece_a_uuid,json=pieceAUuid,proto3" json:"piece_a_uuid,omitempty"`
	PieceBUuid    string                 `protobuf:"bytes,3,opt,name=piece_b_uuid,json=pieceBUuid,proto3" json:"piece_b_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisualHint__MindControl) Reset() {
	*x = VisualHint__MindControl{}
	mi := &file_visual_hint_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisualHint__MindControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisualHint__MindControl) ProtoMessage() {}

func (x *VisualHint__MindControl) ProtoReflect() protoreflect.Message {
	mi := &file_visual_hint_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisualHint__MindControl.ProtoReflect.Descriptor instead.
func (*VisualHint__MindControl) Descriptor() ([]byte, []int) {
	return file_visual_hint_proto_rawDescGZIP(), []int{6}
}

func (x *VisualHint__MindControl) GetPieceAUuid() string {
	if x != nil {
		return x.PieceAUuid
	}
	return ""
}

func (x *VisualHint__MindControl) GetPieceBUuid() string {
	if x != nil {
		return x.PieceBUuid
	}
	return ""
}

// VisualHint__Disintegration indicates a visual effect for a piece disintegrating (e.g. classic chess capture, queen nova).
type VisualHint__Disintegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PieceUuid     string                 `protobuf:"bytes,2,opt,name=piece_uuid,json=pieceUuid,proto3" json:"piece_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisualHint__Disintegration) Reset() {
	*x = VisualHint__Disintegration{}
	mi := &file_visual_hint_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisualHint__Disintegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisualHint__Disintegration) ProtoMessage() {}

func (x *VisualHint__Disintegration) ProtoReflect() protoreflect.Message {
	mi := &file_visual_hint_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisualHint__Disintegration.ProtoReflect.Descriptor instead.
func (*VisualHint__Disintegration) Descriptor() ([]byte, []int) {
	return file_visual_hint_proto_rawDescGZIP(), []int{7}
}

func (x *VisualHint__Disintegration) GetPieceUuid() string {
	if x != nil {
		return x.PieceUuid
	}
	return ""
}

// VisualHint__Yeet indicates a visual effect for a piece being yeeted off the board (e.g. kaboom capture).
type VisualHint__Yeet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PieceUuid     string                 `protobuf:"bytes,2,opt,name=piece_uuid,json=pieceUuid,proto3" json:"piece_uuid,omitempty"`
	YeetVector    *Vector                `protobuf:"bytes,3,opt,name=yeet_vector,json=yeetVector,proto3" json:"yeet_vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisualHint__Yeet) Reset() {
	*x = VisualHint__Yeet{}
	mi := &file_visual_hint_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisualHint__Yeet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisualHint__Yeet) ProtoMessage() {}

func (x *VisualHint__Yeet) ProtoReflect() protoreflect.Message {
	mi := &file_visual_hint_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisualHint__Yeet.ProtoReflect.Descriptor instead.
func (*VisualHint__Yeet) Descriptor() ([]byte, []int) {
	return file_visual_hint_proto_rawDescGZIP(), []int{8}
}

func (x *VisualHint__Yeet) GetPieceUuid() string {
	if x != nil {
		return x.PieceUuid
	}
	return ""
}

func (x *VisualHint__Yeet) GetYeetVector() *Vector {
	if x != nil {
		return x.YeetVector
	}
	return nil
}

var File_visual_hint_proto protoreflect.FileDescriptor

const file_visual_hint_proto_rawDesc = "" +
	"\n" +
	"\x11visual_hint.proto\x12\vkaboomproto\x1a\x0eposition.proto\"\xdf\x04\n" +
	"\n" +
	"VisualHint\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1d\n" +
	"\n" +
	"board_uuid\x18\x02 \x01(\tR\tboardUuid\x12\x16\n" +
	"\x06timing\x18\x03 \x01(\x05R\x06timing\x12B\n" +
	"\tcollision\x18\n" +
	" \x01(\v2\".kaboomproto.VisualHint__CollisionH\x00R\tcollision\x12B\n" +
	"\texplosion\x18\v \x01(\v2\".kaboomproto.VisualHint__ExplosionH\x00R\texplosion\x126\n" +
	"\x05stomp\x18\f \x01(\v2\x1e.kaboomproto.VisualHint__StompH\x00R\x05stomp\x126\n" +
	"\x05snipe\x18\r \x01(\v2\x1e.kaboomproto.VisualHint__SnipeH\x00R\x05snipe\x123\n" +
	"\x04nova\x18\x0e \x01(\v2\x1d.kaboomproto.VisualHint__NovaH\x00R\x04nova\x12I\n" +
	"\fmind_control\x18\x0f \x01(\v2$.kaboomproto.VisualHint__MindControlH\x00R\vmindControl\x12Q\n" +
	"\x0edisintegration\x18\x10 \x01(\v2'.kaboomproto.VisualHint__DisintegrationH\x00R\x0edisintegration\x123\n" +
	"\x04yeet\x18\x11 \x01(\v2\x1d.kaboomproto.VisualHint__YeetH\x00R\x04yeetB\x06\n" +
	"\x04hint\"[\n" +
	"\x15VisualHint__Collision\x12 \n" +
	"\fpiece_a_uuid\x18\x02 \x01(\tR\n" +
	"pieceAUuid\x12 \n" +
	"\fpiece_b_uuid\x18\x03 \x01(\tR\n" +
	"pieceBUuid\"J\n" +
	"\x15VisualHint__Explosion\x121\n" +
	"\bposition\x18\x02 \x01(\v2\x15.kaboomproto.PositionR\bposition\"F\n" +
	"\x11VisualHint__Stomp\x121\n" +
	"\bposition\x18\x01 \x01(\v2\x15.kaboomproto.PositionR\bposition\"e\n" +
	"\x11VisualHint__Snipe\x12)\n" +
	"\x04from\x18\x02 \x01(\v2\x15.kaboomproto.PositionR\x04from\x12%\n" +
	"\x02to\x18\x03 \x01(\v2\x15.kaboomproto.PositionR\x02to\"E\n" +
	"\x10VisualHint__Nova\x121\n" +
	"\bposition\x18\x02 \x01(\v2\x15.kaboomproto.PositionR\bposition\"]\n" +
	"\x17VisualHint__MindControl\x12 \n" +
	"\fpiece_a_uuid\x18\x02 \x01(\tR\n" +
	"pieceAUuid\x12 \n" +
	"\fpiece_b_uuid\x18\x03 \x01(\tR\n" +
	"pieceBUuid\";\n" +
	"\x1aVisualHint__Disintegration\x12\x1d\n" +
	"\n" +
	"piece_uuid\x18\x02 \x01(\tR\tpieceUuid\"g\n" +
	"\x10VisualHint__Yeet\x12\x1d\n" +
	"\n" +
	"piece_uuid\x18\x02 \x01(\tR\tpieceUuid\x124\n" +
	"\vyeet_vector\x18\x03 \x01(\v2\x13.kaboomproto.VectorR\n" +
	"yeetVectorB1Z/github.com/fsufitch/kaboom/proto/go;kaboomprotob\x06proto3"

var (
	file_visual_hint_proto_rawDescOnce sync.Once
	file_visual_hint_proto_rawDescData []byte
)

func file_visual_hint_proto_rawDescGZIP() []byte {
	file_visual_hint_proto_rawDescOnce.Do(func() {
		file_visual_hint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_visual_hint_proto_rawDesc), len(file_visual_hint_proto_rawDesc)))
	})
	return file_visual_hint_proto_rawDescData
}

var file_visual_hint_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_visual_hint_proto_goTypes = []any{
	(*VisualHint)(nil),                 // 0: kaboomproto.VisualHint
	(*VisualHint__Collision)(nil),      // 1: kaboomproto.VisualHint__Collision
	(*VisualHint__Explosion)(nil),      // 2: kaboomproto.VisualHint__Explosion
	(*VisualHint__Stomp)(nil),          // 3: kaboomproto.VisualHint__Stomp
	(*VisualHint__Snipe)(nil),          // 4: kaboomproto.VisualHint__Snipe
	(*VisualHint__Nova)(nil),           // 5: kaboomproto.VisualHint__Nova
	(*VisualHint__MindControl)(nil),    // 6: kaboomproto.VisualHint__MindControl
	(*VisualHint__Disintegration)(nil), // 7: kaboomproto.VisualHint__Disintegration
	(*VisualHint__Yeet)(nil),           // 8: kaboomproto.VisualHint__Yeet
	(*Position)(nil),                   // 9: kaboomproto.Position
	(*Vector)(nil),                     // 10: kaboomproto.Vector
}
var file_visual_hint_proto_depIdxs = []int32{
	1,  // 0: kaboomproto.VisualHint.collision:type_name -> kaboomproto.VisualHint__Collision
	2,  // 1: kaboomproto.VisualHint.explosion:type_name -> kaboomproto.VisualHint__Explosion
	3,  // 2: kaboomproto.VisualHint.stomp:type_name -> kaboomproto.VisualHint__Stomp
	4,  // 3: kaboomproto.VisualHint.snipe:type_name -> kaboomproto.VisualHint__Snipe
	5,  // 4: kaboomproto.VisualHint.nova:type_name -> kaboomproto.VisualHint__Nova
	6,  // 5: kaboomproto.VisualHint.mind_control:type_name -> kaboomproto.VisualHint__MindControl
	7,  // 6: kaboomproto.VisualHint.disintegration:type_name -> kaboomproto.VisualHint__Disintegration
	8,  // 7: kaboomproto.VisualHint.yeet:type_name -> kaboomproto.VisualHint__Yeet
	9,  // 8: kaboomproto.VisualHint__Explosion.position:type_name -> kaboomproto.Position
	9,  // 9: kaboomproto.VisualHint__Stomp.position:type_name -> kaboomproto.Position
	9,  // 10: kaboomproto.VisualHint__Snipe.from:type_name -> kaboomproto.Position
	9,  // 11: kaboomproto.VisualHint__Snipe.to:type_name -> kaboomproto.Position
	9,  // 12: kaboomproto.VisualHint__Nova.position:type_name -> kaboomproto.Position
	10, // 13: kaboomproto.VisualHint__Yeet.yeet_vector:type_name -> kaboomproto.Vector
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_visual_hint_proto_init() }
func file_visual_hint_proto_init() {
	if File_visual_hint_proto != nil {
		return
	}
	file_position_proto_init()
	file_visual_hint_proto_msgTypes[0].OneofWrappers = []any{
		(*VisualHint_Collision)(nil),
		(*VisualHint_Explosion)(nil),
		(*VisualHint_Stomp)(nil),
		(*VisualHint_Snipe)(nil),
		(*VisualHint_Nova)(nil),
		(*VisualHint_MindControl)(nil),
		(*VisualHint_Disintegration)(nil),
		(*VisualHint_Yeet)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_visual_hint_proto_rawDesc), len(file_visual_hint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_visual_hint_proto_goTypes,
		DependencyIndexes: file_visual_hint_proto_depIdxs,
		MessageInfos:      file_visual_hint_proto_msgTypes,
	}.Build()
	File_visual_hint_proto = out.File
	file_visual_hint_proto_goTypes = nil
	file_visual_hint_proto_depIdxs = nil
}
