#!/bin/bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
PROTO_SRC_DIR="$SCRIPT_DIR/src"
TS_DIR="$SCRIPT_DIR/ts"
TS_SRC_DIR="$TS_DIR/src"

PROTOC=$(type -p protoc || true)
if [ -z "$PROTOC" ]; then
    echo "protoc not found in PATH. Please install the Protocol Buffers compiler."
    exit 1
fi

PROTOC_GEN_TS_PROTO="$TS_DIR/node_modules/.bin/protoc-gen-ts_proto"
if [ ! -x "$PROTOC_GEN_TS_PROTO" ]; then
    echo "ts-proto plugin not found at $PROTOC_GEN_TS_PROTO."
    echo "Hint: run 'npm install' inside proto/ts to install dependencies."
    exit 1
fi

echo "Generating TypeScript code from .proto files..."
echo "  Using protoc: $PROTOC"
echo "  Using ts-proto: $PROTOC_GEN_TS_PROTO"

rm -rf "$TS_SRC_DIR"
mkdir -p "$TS_SRC_DIR"

(
    set -ex
    $PROTOC \
        --plugin=protoc-gen-ts_proto="$PROTOC_GEN_TS_PROTO" \
        --ts_proto_out="$TS_SRC_DIR" \
        --ts_proto_opt=esModuleInterop=true,outputServices=generic-definitions,useOptionals=messages,env=node \
        --proto_path="$PROTO_SRC_DIR" \
        "$PROTO_SRC_DIR"/*.proto
)

INDEX_FILE="$TS_SRC_DIR/index.ts"
shopt -s nullglob
{
    echo "// Code generated by protobuf_ts.sh. DO NOT EDIT."
    echo
    for file in "$TS_SRC_DIR"/*.ts; do
        base=$(basename "$file" .ts)
        if [ "$base" = "index" ]; then
            continue
        fi
        identifier=${base//[^a-zA-Z0-9_]/_}
        if [[ $identifier =~ ^[0-9] ]]; then
            identifier="_$identifier"
        fi
        echo "export * as $identifier from \"./$base\";"
    done
} > "$INDEX_FILE"
shopt -u nullglob

echo "Building TypeScript package..."
(
    cd "$TS_DIR"
    npm run build
)
