syntax = "proto3";

package proto;

import "board.proto";
import "piece.proto";

message ClassicChessMove {
  oneof piece {
    Pawn pawn = 1;
    Rook rook = 2;
    Knight knight = 3;
    Bishop bishop = 4;
    Queen queen = 5;
    King king = 6;
  }

  message Pawn {
    oneof type {
      OneStep one_step = 1;
      TwoStep two_step = 2;
      Capture capture = 3;
      EnPassant en_passant = 4;
      Promotion promotion = 5;
    }

    message OneStep {
      Place from = 1;
    }
    message TwoStep {
      Place from = 1;
    }
    message Capture {
      Place from = 1;
      Place to = 2;
    }
    message EnPassant {
      Place from = 1;
      Place to = 2;
    }
    message Promotion {
      Place from = 1;
      ChessPieceKind promote_to = 2;
    }
  }

  message Rook {
    oneof type{
      Move move = 1;
      Capture capture = 2;
    }

    message Move {
      Place from = 1;
      Place to = 2;
    }
    message Capture {
      Place from = 1;
      Place to = 2;
    }
  }

  message Knight {
    oneof type{
      Move move = 1;
      Capture capture = 2;
    }

    message Move {
      Place from = 1;
      Place to = 2;
    }
    message Capture {
      Place from = 1;
      Place to = 2;
    }
  }

  message Bishop {
    oneof type {
      Move move = 1;
      Capture capture = 2;
    }

    message Move {
      Place from = 1;
      Place to = 2;
    }
    message Capture {
      Place from = 1;
      Place to = 2;
    }
  }

  message Queen {
    oneof type {
      Move move = 1;
      Capture capture = 2;
    }

    message Move {
      Place from = 1;
      Place to = 2;
    }
    message Capture {
      Place from = 1;
      Place to = 2;
    }
  }

  message King {
    oneof type{
      Move move = 1;
      Capture capture = 2;
      Castle castle = 3;
    }

    message Move {
      Place from = 1;
      Place to = 2;
    }
    message Capture {
      Place from = 1;
      Place to = 2;
    }
    message Castle {
      Place king_from = 1;
      Place king_to = 2;
      Place rook_from = 3;
      Place rook_to = 4;
    }
  }
}

